// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { BadgeStatus } from './BadgeStatus';

import { BadgeStatusSize, BadgeStatusStatus } from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of BadgeStatus component
 */

figma.connect(
  BadgeStatus,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=623-3377',
  {
    props: {
      size: figma.enum('size', {
        Md: BadgeStatusSize.Md,
        Lg: BadgeStatusSize.Lg,
      }),
      status: figma.enum('status', {
        Active: BadgeStatusStatus.Active,
        Inactive: BadgeStatusStatus.Inactive,
        Disconnected: BadgeStatusStatus.Disconnected,
        New: BadgeStatusStatus.New,
        Attention: BadgeStatusStatus.Attention,
      }),
      hasBorder: figma.boolean('hasBorder'),
    },
    example: (props) => <BadgeStatus {...props} />,
  },
);
