// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { SectionDivider } from './SectionDivider';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of SectionDivider component
 */
figma.connect(
  SectionDivider,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=15701-23',
  {
    props: {},
    example: () => <SectionDivider />,
  },
);
