// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import { IconAlertSeverity } from '@metamask/design-system-shared';
import React from 'react';

import { TitleAlert } from './TitleAlert';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of TitleAlert.
 */

figma.connect(
  TitleAlert,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=14851-114',
  {
    props: {
      severity: figma.enum('severity', {
        Warning: IconAlertSeverity.Warning,
        Info: IconAlertSeverity.Info,
        Success: IconAlertSeverity.Success,
        Danger: IconAlertSeverity.Danger,
      }),
      title: figma.string('title'),
      description: figma.string('description'),
    },
    example: ({ severity, title, description }) => (
      <TitleAlert severity={severity} title={title} description={description} />
    ),
  },
);
