// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { HeaderSearch } from './HeaderSearch';

import { HeaderSearchVariant } from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of HeaderSearch
 */

const HEADER_SEARCH_URL =
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=15746-578';

figma.connect(HeaderSearch, HEADER_SEARCH_URL, {
  variant: { variant: 'screen' },
  props: {
    placeholder: figma.nestedProps('Search Placeholder', {
      label: figma.string('Label text'),
    }),
  },
  example: ({ placeholder }) => (
    <HeaderSearch
      variant={HeaderSearchVariant.Screen}
      onPressBackButton={() => undefined}
      textFieldSearchProps={{
        value: '',
        onChangeText: () => undefined,
        onPressClearButton: () => undefined,
        placeholder: placeholder.label,
      }}
    />
  ),
});

figma.connect(HeaderSearch, HEADER_SEARCH_URL, {
  variant: { variant: 'inline' },
  props: {
    placeholder: figma.nestedProps('Search Placeholder', {
      label: figma.string('Label text'),
    }),
  },
  example: ({ placeholder }) => (
    <HeaderSearch
      variant={HeaderSearchVariant.Inline}
      onPressCancelButton={() => undefined}
      textFieldSearchProps={{
        value: '',
        onChangeText: () => undefined,
        onPressClearButton: () => undefined,
        placeholder: placeholder.label,
      }}
    />
  ),
});
