// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { AvatarAccount, AvatarAccountSize } from '../AvatarAccount';
import { BadgeNetwork } from '../BadgeNetwork';

import { BadgeWrapper } from './BadgeWrapper';

import { BadgeWrapperPosition, BadgeWrapperPositionAnchorShape } from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React web implementation of BadgeWrapper component
 */

figma.connect(
  BadgeWrapper,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=18365-23780',
  {
    props: {
      position: figma.enum('position', {
        'top-right': BadgeWrapperPosition.TopRight,
        'top-left': BadgeWrapperPosition.TopLeft,
        'bottom-right': BadgeWrapperPosition.BottomRight,
        'bottom-left': BadgeWrapperPosition.BottomLeft,
      }),
    },
    example: ({ position }) => (
      <BadgeWrapper
        position={position}
        positionAnchorShape={BadgeWrapperPositionAnchorShape.Circular}
        badge={
          <BadgeNetwork name="ETH" src="./assets/network-icons/ethereum.svg" />
        }
      >
        <AvatarAccount
          address="0x9Cbf7c41B7787F6c621115010D3B044029FE2Ce8"
          size={AvatarAccountSize.Md}
        />
      </BadgeWrapper>
    ),
  },
);
