// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { IconName } from '../Icon';

import { MainActionButton } from './MainActionButton';

/* -- This file was auto-generated by Code Connect -- */
figma.connect(
  MainActionButton,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=15793-13',
  {
    props: {
      label: figma.string('label'),
      isDisabled: figma.enum('isDisabled', {
        false: false,
        true: true,
      }),
    },
    example: ({ label, isDisabled }) => (
      <MainActionButton
        iconName={IconName.Add}
        label={label}
        isDisabled={isDisabled}
        onPress={() => undefined}
      />
    ),
  },
);
