// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { AvatarGroup } from './AvatarGroup';

import { AvatarGroupSize, AvatarGroupVariant } from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React web implementation of AvatarGroup component
 */

figma.connect(
  AvatarGroup,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=310-2005',
  {
    props: {
      size: figma.enum('size', {
        Xs: AvatarGroupSize.Xs,
        Sm: AvatarGroupSize.Sm,
        Md: AvatarGroupSize.Md,
        Lg: AvatarGroupSize.Lg,
        Xl: AvatarGroupSize.Xl,
      }),
      variant: figma.enum('variant', {
        Tokens: AvatarGroupVariant.Token,
        Accounts: AvatarGroupVariant.Account,
        Networks: AvatarGroupVariant.Network,
        Favicons: AvatarGroupVariant.Favicon,
      }),
    },
    example: ({ size, variant }) => (
      <AvatarGroup
        variant={variant}
        size={size}
        avatarPropsArr={[
          { name: 'Uniswap', src: 'https://uniswap.org/favicon.ico' },
          { name: 'Aave', src: 'https://aave.com/favicon.ico' },
          { name: 'GitHub', src: 'https://github.com/favicon.ico' },
          { name: 'MetaMask', src: 'https://metamask.io/favicon.ico' },
        ]}
      />
    ),
  },
);
