// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { ButtonFilter } from './ButtonFilter';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of ButtonFilter component
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ButtonFilter,
  'https://www.figma.com/design/2n1zkGJ0z04x5JgqMS1tyZ/refactor--Buttons?node-id=19220-15',
  {
    props: {
      children: figma.string('label'),
      isActive: figma.boolean('isActive', {
        true: true,
        false: undefined,
      }),
    },
    example: ({ children, isActive }) => (
      <ButtonFilter isActive={isActive} onPress={() => undefined}>
        {children}
      </ButtonFilter>
    ),
  },
);
