/**
 * Icon - color (ADR-0003)
 * All icon color values shared across React and React Native platforms.
 */
export const IconColor = {
  /** For default neutral icons */
  IconDefault: 'text-icon-default',
  /** For softer neutral icons */
  IconAlternative: 'text-icon-alternative',
  /** For the weakest contrast neutral icons (not accessible) */
  IconMuted: 'text-icon-muted',
  /** For elements used on top of icon/default fills (e.g. checkmark on monochromatic checkbox) */
  IconInverse: 'text-icon-inverse',
  /** For elements used on top of overlay/alternative. Used for text, icon, or border */
  OverlayInverse: 'text-overlay-inverse',
  /** For interactive, active, and selected semantics. Used for text, background, icon, or border */
  PrimaryDefault: 'text-primary-default',
  /** For softer variants of primary interactive elements */
  PrimaryAlternative: 'text-primary-alternative',
  /** For elements used on top of primary/default. Used for text, icon, or border */
  PrimaryInverse: 'text-primary-inverse',
  /** For critical alert semantic elements. Used for text, background, icon, or border */
  ErrorDefault: 'text-error-default',
  /** For softer variants of error elements */
  ErrorAlternative: 'text-error-alternative',
  /** For elements used on top of error/default. Used for text, icon, or border */
  ErrorInverse: 'text-error-inverse',
  /** For caution alert semantic elements. Used for text, background, icon, or border */
  WarningDefault: 'text-warning-default',
  /** For elements used on top of warning/default. Used for text, icon, or border */
  WarningInverse: 'text-warning-inverse',
  /** For positive semantic elements. Used for text, background, icon, or border */
  SuccessDefault: 'text-success-default',
  /** For elements used on top of success/default. Used for text, icon, or border */
  SuccessInverse: 'text-success-inverse',
  /** For informational read-only elements. Used for text, background, icon, or border */
  InfoDefault: 'text-info-default',
  /** For elements used on top of info/default. Used for text, icon, or border */
  InfoInverse: 'text-info-inverse',
} as const;

export type IconColor = (typeof IconColor)[keyof typeof IconColor];

// /////////////////////////////////////////////////////
// DO NOT EDIT - generated by generate-icons.ts
// /////////////////////////////////////////////////////

/**
 * Icon - name
 * All icon names shared across React and React Native platforms.
 * This block is auto-generated — do not edit directly.
 * Run `yarn generate:icons` from the repo root to regenerate.
 */
export const IconName = {
  Accessibility: 'Accessibility',
  Activity: 'Activity',
  AddCircle: 'AddCircle',
  AddSquare: 'AddSquare',
  Add: 'Add',
  AfterHours: 'AfterHours',
  Ai: 'Ai',
  AppleLogo: 'AppleLogo',
  Apps: 'Apps',
  Arrow2Down: 'Arrow2Down',
  Arrow2Left: 'Arrow2Left',
  Arrow2Right: 'Arrow2Right',
  Arrow2UpRight: 'Arrow2UpRight',
  Arrow2Up: 'Arrow2Up',
  ArrowDoubleRight: 'ArrowDoubleRight',
  ArrowDown: 'ArrowDown',
  ArrowLeft: 'ArrowLeft',
  ArrowRight: 'ArrowRight',
  ArrowUp: 'ArrowUp',
  AttachMoney: 'AttachMoney',
  Backspace: 'Backspace',
  Ban: 'Ban',
  Bank: 'Bank',
  Book: 'Book',
  Bookmark: 'Bookmark',
  Bridge: 'Bridge',
  BuySell: 'BuySell',
  Calculator: 'Calculator',
  Calendar: 'Calendar',
  Call: 'Call',
  Camera: 'Camera',
  Campaign: 'Campaign',
  CandlestickFilled: 'CandlestickFilled',
  Candlestick: 'Candlestick',
  Card: 'Card',
  Cash: 'Cash',
  Category: 'Category',
  Chart: 'Chart',
  CheckBold: 'CheckBold',
  Check: 'Check',
  CircleX: 'CircleX',
  ClockFilled: 'ClockFilled',
  Clock: 'Clock',
  Close: 'Close',
  Code: 'Code',
  Coin: 'Coin',
  Collapse: 'Collapse',
  Confirmation: 'Confirmation',
  Connect: 'Connect',
  CopySuccess: 'CopySuccess',
  Copy: 'Copy',
  Customize: 'Customize',
  Danger: 'Danger',
  Data: 'Data',
  Details: 'Details',
  Diagram: 'Diagram',
  DocumentCode: 'DocumentCode',
  Download: 'Download',
  Edit: 'Edit',
  Error: 'Error',
  Ethereum: 'Ethereum',
  Exchange: 'Exchange',
  Expand: 'Expand',
  Explore: 'Explore',
  Export: 'Export',
  Extension: 'Extension',
  EyeSlash: 'EyeSlash',
  Eye: 'Eye',
  FaceId: 'FaceId',
  Feedback: 'Feedback',
  File: 'File',
  Filter: 'Filter',
  Fingerprint: 'Fingerprint',
  Fire: 'Fire',
  Flag: 'Flag',
  FlashFilled: 'FlashFilled',
  Flash: 'Flash',
  Flask: 'Flask',
  Forest: 'Forest',
  FullCircle: 'FullCircle',
  Gas: 'Gas',
  Gift: 'Gift',
  GlobalSearch: 'GlobalSearch',
  Global: 'Global',
  Hardware: 'Hardware',
  Hierarchy: 'Hierarchy',
  HomeFilled: 'HomeFilled',
  Home: 'Home',
  Image: 'Image',
  Info: 'Info',
  Keep: 'Keep',
  Key: 'Key',
  Link: 'Link',
  ListArrow: 'ListArrow',
  Loading: 'Loading',
  Location: 'Location',
  LockSlash: 'LockSlash',
  Lock: 'Lock',
  Logout: 'Logout',
  Mail: 'Mail',
  Menu: 'Menu',
  Merge: 'Merge',
  MessageQuestion: 'MessageQuestion',
  Messages: 'Messages',
  MetamaskFoxOutline: 'MetamaskFoxOutline',
  MinusBold: 'MinusBold',
  Minus: 'Minus',
  Mobile: 'Mobile',
  MoneyBag: 'MoneyBag',
  Monitor: 'Monitor',
  MoreHorizontal: 'MoreHorizontal',
  MoreVertical: 'MoreVertical',
  MusdFilled: 'MusdFilled',
  Musd: 'Musd',
  NoPhotography: 'NoPhotography',
  Notification: 'Notification',
  People: 'People',
  Pin: 'Pin',
  Plant: 'Plant',
  Plug: 'Plug',
  PopUp: 'PopUp',
  Predictions: 'Predictions',
  ProgrammingArrows: 'ProgrammingArrows',
  QrCode: 'QrCode',
  Question: 'Question',
  Receive: 'Receive',
  Received: 'Received',
  Refresh: 'Refresh',
  RemoveMinus: 'RemoveMinus',
  Rocket: 'Rocket',
  Save: 'Save',
  ScanBarcode: 'ScanBarcode',
  Scan: 'Scan',
  Search: 'Search',
  SecurityKey: 'SecurityKey',
  SecuritySearch: 'SecuritySearch',
  SecuritySlash: 'SecuritySlash',
  SecurityTick: 'SecurityTick',
  SecurityTime: 'SecurityTime',
  Security: 'Security',
  Send: 'Send',
  Setting: 'Setting',
  Share: 'Share',
  ShieldLock: 'ShieldLock',
  SidePanel: 'SidePanel',
  Sms: 'Sms',
  SnapsMobile: 'SnapsMobile',
  Snaps: 'Snaps',
  Sparkle: 'Sparkle',
  Speed: 'Speed',
  Speedometer: 'Speedometer',
  Stake: 'Stake',
  StarFilled: 'StarFilled',
  Star: 'Star',
  SwapHorizontal: 'SwapHorizontal',
  SwapVertical: 'SwapVertical',
  Tag: 'Tag',
  Telegram: 'Telegram',
  ThumbDownFilled: 'ThumbDownFilled',
  ThumbDown: 'ThumbDown',
  ThumbUpFilled: 'ThumbUpFilled',
  ThumbUp: 'ThumbUp',
  Tint: 'Tint',
  Trash: 'Trash',
  TrendDown: 'TrendDown',
  TrendUp: 'TrendUp',
  Trophy: 'Trophy',
  Unpin: 'Unpin',
  Upload: 'Upload',
  Usb: 'Usb',
  UserCheck: 'UserCheck',
  UserCircleAdd: 'UserCircleAdd',
  UserCircleRemove: 'UserCircleRemove',
  UserCircle: 'UserCircle',
  VerifiedFilled: 'VerifiedFilled',
  Videocam: 'Videocam',
  Wallet: 'Wallet',
  Warning: 'Warning',
  WebTraffic: 'WebTraffic',
  WifiOff: 'WifiOff',
  Wifi: 'Wifi',
  X: 'X',
} as const;

export type IconName = (typeof IconName)[keyof typeof IconName];

// END generated IconName

/**
 * Icon - size
 * Common icon sizes shared across React and React Native platforms.
 */
export const IconSize = {
  /** Extra small - 12px */
  Xs: 'xs',
  /** Small - 16px */
  Sm: 'sm',
  /** Medium - 20px (Default) */
  Md: 'md',
  /** Large - 24px */
  Lg: 'lg',
  /** Extra large - 32px */
  Xl: 'xl',
} as const;

export type IconSize = (typeof IconSize)[keyof typeof IconSize];

/**
 * Icon component shared props (ADR-0004).
 */
export type IconPropsShared = {
  /**
   * Required prop to specify which icon to render from the icon set.
   */
  name: IconName;
  /**
   * Optional prop that sets the color of the icon using predefined theme colors.
   *
   * @default IconColor.IconDefault
   */
  color?: IconColor;
  /**
   * Optional prop to control the size of the icon.
   * Different sizes map to specific pixel dimensions.
   *
   * @default IconSize.Md
   */
  size?: IconSize;
};
