// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { BannerAlert } from './BannerAlert';

import { BannerAlertSeverity } from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React web implementation of BannerAlert component
 */

figma.connect(
  BannerAlert,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=9315-372',
  {
    props: {
      severity: figma.enum('severity', {
        Info: BannerAlertSeverity.Info,
        Success: BannerAlertSeverity.Success,
        Warning: BannerAlertSeverity.Warning,
        Danger: BannerAlertSeverity.Danger,
      }),
      title: figma.string('Title'),
      description: figma.string('Description'),
    },
    example: ({ severity, title, description, ...props }) => (
      <BannerAlert
        severity={severity}
        title={title}
        description={description}
        {...props}
      />
    ),
  },
);
