// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { BannerAlert } from './BannerAlert';

import { BannerAlertSeverity } from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React implementation of BannerAlert
 */
figma.connect(
  BannerAlert,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=16610-22779',
  {
    props: {
      severity: figma.enum('severity', {
        Info: BannerAlertSeverity.Info,
        Success: BannerAlertSeverity.Success,
        Warning: BannerAlertSeverity.Warning,
        Danger: BannerAlertSeverity.Danger,
        Neutral: BannerAlertSeverity.Neutral,
      }),
      bannerBase: figma.nestedProps('BannerBase', {
        title: figma.string('title'),
        description: figma.string('description'),
        actionButton: figma.boolean('action', {
          true: figma.nestedProps('ButtonBase', {
            label: figma.string('label'),
          }),
          false: { label: undefined },
        }),
        actionButtonOnClick: figma.boolean('action', {
          true: () => undefined,
          false: undefined,
        }),
        onClose: figma.boolean('close', {
          true: () => undefined,
          false: undefined,
        }),
      }),
    },
    example: ({ severity, bannerBase }) => (
      <BannerAlert
        severity={severity}
        title={bannerBase.title}
        description={bannerBase.description}
        actionButtonLabel={bannerBase.actionButton.label}
        actionButtonOnClick={bannerBase.actionButtonOnClick}
        onClose={bannerBase.onClose}
      />
    ),
  },
);
