// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { AvatarNetwork } from './AvatarNetwork';

import { AvatarNetworkSize } from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React web implementation of AvatarNetwork component
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  AvatarNetwork,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-WIP--MMDS-Components?node-id=196%3A1563',
  {
    props: {
      size: figma.enum('size', {
        Xs: AvatarNetworkSize.Xs,
        Sm: AvatarNetworkSize.Sm,
        Md: AvatarNetworkSize.Md,
        Lg: AvatarNetworkSize.Lg,
        Xl: AvatarNetworkSize.Xl,
      }),
    },
    example: (props) => (
      <AvatarNetwork
        name="Ethereum"
        src="./assets/network-icons/ethereum.svg"
        {...props}
      />
    ),
  },
);
