compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

enableTelemetry: 0

logFilters:
  - code: YN0004
    level: discard

nmHoistingLimits: none

nodeLinker: node-modules

npmMinimalAgeGate: 4320

npmPreapprovedPackages:
  - "@metamask/*"
  - "@lavamoat/*"
  - "@storybook/*"
  - "@chromatic-com/*"
  - storybook
  - eslint-plugin-storybook
  - "@chromatic-com/storybook"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-allow-scripts.cjs
    spec: "https://raw.githubusercontent.com/LavaMoat/LavaMoat/main/packages/yarn-plugin-allow-scripts/bundles/@yarnpkg/plugin-allow-scripts.js"
