compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

enableTelemetry: 0

logFilters:
  - code: YN0004
    level: discard

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-allow-scripts.cjs
    spec: 'https://raw.githubusercontent.com/LavaMoat/LavaMoat/main/packages/yarn-plugin-allow-scripts/bundles/@yarnpkg/plugin-allow-scripts.js'

nmHoistingLimits: none

# NPM Supply Chain Attack Protection
# Minimum age gate: only allow packages older than 3 days (4320 minutes)
npmMinimalAgeGate: 4320

# Pre-approved packages that can bypass the age gate
npmPreapprovedPackages:
  - '@metamask/*'
  - '@lavamoat/*'
