import codeConnect from '@figma/code-connect';
import React from 'react';

import { AvatarAccountSize } from '../../types';

import { AvatarAccount } from './AvatarAccount';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of AvatarAccount component
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

codeConnect.connect(
  AvatarAccount,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-WIP--MMDS-Components?node-id=128%3A1673',
  {
    props: {
      size: codeConnect.enum('size', {
        Xs: AvatarAccountSize.Xs,
        Sm: AvatarAccountSize.Sm,
        Md: AvatarAccountSize.Md,
        Lg: AvatarAccountSize.Lg,
        Xl: AvatarAccountSize.Xl,
      }),
      // Note: Badge mapping is not implemented yet as AvatarAccount doesn't have a badge prop
      // This might be handled by a separate BadgeWrapper component
      // "badge": figma.enum('Badge', {
      //   "none": "none",
      //   "Network": "network",
      //   "Connection": "connection"
      // })
    },
    example: (props) => (
      <AvatarAccount
        address="0x9Cbf7c41B7787F6c621115010D3B044029FE2Ce8"
        {...props}
      />
    ),
  },
);
