// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import { SegmentedControlSize } from '@metamask/design-system-shared';
import React, { useEffect, useState } from 'react';

import { FilterButton } from '../FilterButton';

import { SegmentedControl } from './SegmentedControl';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of SegmentedControl component.
 *
 * `value` and `onChange` are runtime-only; selection is reflected via child
 * FilterButton `isSelected` in Figma.
 */

figma.connect(
  SegmentedControl,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=16499-254',
  {
    props: {
      size: figma.enum('size', {
        Sm: SegmentedControlSize.Sm,
        Md: SegmentedControlSize.Md,
        Lg: SegmentedControlSize.Lg,
      }),
      isFullWidth: figma.enum('isFullWidth', {
        true: true,
        false: false,
      }),
      selectedSegment: figma.nestedProps('FilterButton', {
        isSelected: figma.enum('isSelected', {
          true: true,
          false: false,
        }),
      }),
      segmentLabel: figma.nestedProps('_ButtonBase', {
        label: figma.string('label'),
      }),
    },
    example: ({ size, isFullWidth, selectedSegment, segmentLabel }) => {
      const selectedValue = 'selected';
      const unselectedValue = 'unselected';
      const figmaValue = selectedSegment.isSelected
        ? selectedValue
        : unselectedValue;
      const [value, setValue] = useState(figmaValue);

      useEffect(() => {
        setValue(figmaValue);
      }, [figmaValue]);

      return (
        <SegmentedControl
          value={value}
          onChange={setValue}
          size={size}
          isFullWidth={isFullWidth}
        >
          <FilterButton value={selectedValue} onPress={() => undefined}>
            {segmentLabel.label}
          </FilterButton>
          <FilterButton value={unselectedValue} onPress={() => undefined}>
            Unselected
          </FilterButton>
        </SegmentedControl>
      );
    },
  },
);
