// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import {
  FontWeight,
  TextColor,
  TextVariant,
} from '@metamask/design-system-shared';
import React from 'react';

import { Box, BoxAlignItems, BoxFlexDirection } from '../Box';
import { Icon, IconColor, IconName, IconSize } from '../Icon';
import { Text } from '../Text';

import { TitleStandard } from './TitleStandard';

const BottomRowVariant = {
  BottomLabel: 'bottomLabel',
  BottomAccessory: 'bottomAccessory',
} as const;

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of TitleStandard component.
 *
 * - `topAccessory` and `titleEndAccessory` are visibility toggles in Figma;
 *   the example uses placeholder `Text` and `Icon` children when enabled.
 * - `bottomLabel`, `bottomLabelEndAccessory`, and `bottomAccessory` come from
 *   nested `_BottomRow` via its `variant` enum.
 * - `bottomRow [Figma Only]` is omitted (design composition only).
 */

figma.connect(
  TitleStandard,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=15535-3398',
  {
    props: {
      title: figma.string('title'),
      topAccessory: figma.boolean('topAccessory'),
      titleEndAccessory: figma.boolean('titleEndAccessory'),
      bottomRow: figma.nestedProps('_BottomRow', {
        variant: figma.enum('variant', {
          bottomLabel: BottomRowVariant.BottomLabel,
          bottomAccessory: BottomRowVariant.BottomAccessory,
        }),
        bottomLabel: figma.string('bottomLabel'),
        bottomLabelEndAccessory: figma.boolean('bottomLabelEndAccessory'),
      }),
    },
    example: ({ title, topAccessory, titleEndAccessory, bottomRow }) => {
      const resolvedTopAccessory = topAccessory ? (
        <Text
          variant={TextVariant.BodySm}
          fontWeight={FontWeight.Medium}
          color={TextColor.TextAlternative}
        >
          Step 2 of 3
        </Text>
      ) : undefined;

      const resolvedTitleEndAccessory = titleEndAccessory ? (
        <Icon
          name={IconName.Info}
          size={IconSize.Sm}
          color={IconColor.IconAlternative}
        />
      ) : undefined;

      const isBottomLabelVariant =
        bottomRow.variant === BottomRowVariant.BottomLabel;
      const isBottomAccessoryVariant =
        bottomRow.variant === BottomRowVariant.BottomAccessory;

      const resolvedBottomLabel =
        isBottomLabelVariant && bottomRow.bottomLabel
          ? bottomRow.bottomLabel
          : undefined;

      const resolvedBottomLabelEndAccessory =
        isBottomLabelVariant && bottomRow.bottomLabelEndAccessory ? (
          <Icon
            name={IconName.Info}
            size={IconSize.Sm}
            color={IconColor.IconAlternative}
          />
        ) : undefined;

      const resolvedBottomAccessory = isBottomAccessoryVariant ? (
        <Box
          flexDirection={BoxFlexDirection.Row}
          alignItems={BoxAlignItems.Center}
          gap={1}
        >
          <Icon name={IconName.SecurityAlert} size={IconSize.Xs} />
          <Text variant={TextVariant.BodySm}>
            MetaMask support will never ask for your phrase.
          </Text>
        </Box>
      ) : undefined;

      return (
        <TitleStandard
          title={title}
          topAccessory={resolvedTopAccessory}
          titleEndAccessory={resolvedTitleEndAccessory}
          bottomLabel={resolvedBottomLabel}
          bottomLabelEndAccessory={resolvedBottomLabelEndAccessory}
          bottomAccessory={resolvedBottomAccessory}
        />
      );
    },
  },
);
