// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { TitleStandard } from './TitleStandard';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of TitleStandard component.
 */

figma.connect(
  TitleStandard,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=15535-3398',
  {
    props: {
      title: figma.string('title'),
      topAccessory: figma.slot('TopAccessory'),
      titleEndAccessory: figma.boolean('titleEndAccessory', {
        true: figma.children('titleEndAccessory'),
        false: undefined,
      }),
      bottomLabel: figma.textContent('bottomLabel'),
      bottomLabelEndAccessory: figma.boolean('bottomLabelEndAccessory', {
        true: figma.children('bottomLabelEndAccessory'),
        false: undefined,
      }),
    },
    example: ({
      title,
      topAccessory,
      titleEndAccessory,
      bottomLabel,
      bottomLabelEndAccessory,
    }) => (
      <TitleStandard
        title={title}
        topAccessory={topAccessory}
        titleEndAccessory={titleEndAccessory}
        bottomLabel={bottomLabel}
        bottomLabelEndAccessory={bottomLabelEndAccessory}
      />
    ),
  },
);
