// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { Switch } from './Switch';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of Switch component.
 *
 * - `hasLabel` toggles the optional label text in Figma.
 * - `isOn` and `isDisabled` come from nested `RNSwitch` variant axes.
 */

figma.connect(
  Switch,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=16017-31',
  {
    props: {
      hasLabel: figma.boolean('hasLabel'),
      label: figma.string('label'),
      rnSwitch: figma.nestedProps('RNSwitch', {
        isOn: figma.enum('isOn', {
          true: true,
          false: false,
        }),
        isDisabled: figma.enum('isDisabled', {
          true: true,
          false: false,
        }),
      }),
    },
    example: ({ hasLabel, label, rnSwitch }) => {
      const resolvedLabel = hasLabel ? label : undefined;

      return (
        <Switch
          isOn={rnSwitch.isOn}
          isDisabled={rnSwitch.isDisabled}
          label={resolvedLabel}
          onValueChange={() => {}}
        />
      );
    },
  },
);
