// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { AvatarGroup } from './AvatarGroup';

import { AvatarGroupSize, AvatarGroupVariant } from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of AvatarGroup component
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  AvatarGroup,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-WIP--MMDS-Components?node-id=310%3A2005',
  {
    props: {
      size: figma.enum('size', {
        Xs: AvatarGroupSize.Xs,
        Sm: AvatarGroupSize.Sm,
        Md: AvatarGroupSize.Md,
        Lg: AvatarGroupSize.Lg,
        Xl: AvatarGroupSize.Xl,
      }),
      variant: figma.enum('variant', {
        Tokens: AvatarGroupVariant.Token,
        Accounts: AvatarGroupVariant.Account,
        Networks: AvatarGroupVariant.Network,
        Favicons: AvatarGroupVariant.Favicon,
      }),
      isReverse: figma.boolean('isReverse'),
    },
    example: ({ variant, isReverse, ...props }) => (
      <AvatarGroup
        variant={variant}
        avatarPropsArr={
          [
            /** Add avatar prop objects here */
          ]
        }
        isReverse={isReverse}
        {...props}
      />
    ),
  },
);
