import * as fs from 'fs/promises';
import * as path from 'path';

/* eslint-disable n/no-process-env -- CLI script reads FIGMA_ACCESS_TOKEN from the environment */

const REPO_ROOT = path.join(__dirname, '../../..');
const FIGMA_FILE_KEY = '1D6tnzXqWgnUC3spaAOELN';
const FIGMA_FILE_URL = `https://www.figma.com/design/${FIGMA_FILE_KEY}/%F0%9F%A6%8A-MMDS-Components`;
const SHARED_TYPES_FILE = path.join(
  __dirname,
  '../src/types/Icon/Icon.types.ts',
);

const OUTPUT_PATHS = [
  path.join(
    REPO_ROOT,
    'packages/design-system-react/src/components/Icon/IconGlyphs.figma.tsx',
  ),
  path.join(
    REPO_ROOT,
    'packages/design-system-react-native/src/components/Icon/IconGlyphs.figma.tsx',
  ),
];

type FigmaComponentMeta = {
  name: string;
  node_id: string;
};

function toPascalCase(figmaName: string): string {
  return figmaName
    .split('-')
    .map((part) => `${part[0]?.toUpperCase() ?? ''}${part.slice(1)}`)
    .join('');
}

function readIconNameKeys(typesSource: string): Set<string> {
  const keys = new Set<string>();
  let inBlock = false;

  for (const line of typesSource.split('\n')) {
    if (line.includes('export const IconName')) {
      inBlock = true;
      continue;
    }
    if (!inBlock) {
      continue;
    }
    if (line.trim().startsWith('} as const')) {
      break;
    }
    const match = line.match(/^\s+(\w+):/u);
    if (match) {
      keys.add(match[1]);
    }
  }

  return keys;
}

function nodeIdToQueryParam(nodeId: string): string {
  return nodeId.replace(':', '-');
}

async function fetchFigmaComponents(): Promise<FigmaComponentMeta[]> {
  const token = process.env.FIGMA_ACCESS_TOKEN;
  if (!token) {
    throw new Error(
      'FIGMA_ACCESS_TOKEN is required. Add it to .env at the repo root.',
    );
  }

  const response = await fetch(
    `https://api.figma.com/v1/files/${FIGMA_FILE_KEY}/components`,
    {
      headers: {
        'X-Figma-Token': token,
      },
    },
  );

  if (!response.ok) {
    throw new Error(
      `Figma API error ${response.status}: ${await response.text()}`,
    );
  }

  const data = (await response.json()) as {
    meta?: { components?: FigmaComponentMeta[] };
  };

  return data.meta?.components ?? [];
}

function isIconGlyphName(name: string): boolean {
  return /^[a-z0-9-]+$/u.test(name);
}

function buildOutputFile(
  connects: { figmaName: string; iconNameKey: string; nodeId: string }[],
): string {
  const connectBlocks = connects
    .map(
      ({ iconNameKey, nodeId }) => `figma.connect(
  '${FIGMA_FILE_URL}?node-id=${nodeIdToQueryParam(nodeId)}',
  {
    example: () => IconName.${iconNameKey},
  },
);`,
    )
    .join('\n\n');

  return `// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';

import { IconName } from '.';

// /////////////////////////////////////////////////////
// DO NOT EDIT - generated by generate-icon-figma-connect.ts
// Maps Figma icon glyph components to IconName for figma.instance() swaps.
// Regenerate: yarn generate:icon-figma-connect
// /////////////////////////////////////////////////////

${connectBlocks}
`;
}

async function main(): Promise<void> {
  const typesSource = await fs.readFile(SHARED_TYPES_FILE, 'utf8');
  const iconNameKeys = readIconNameKeys(typesSource);
  const components = await fetchFigmaComponents();

  const mapped: {
    figmaName: string;
    iconNameKey: string;
    nodeId: string;
  }[] = [];
  const unmapped: string[] = [];

  for (const component of components) {
    if (!isIconGlyphName(component.name)) {
      continue;
    }

    const iconNameKey = toPascalCase(component.name);
    if (!iconNameKeys.has(iconNameKey)) {
      unmapped.push(component.name);
      continue;
    }

    mapped.push({
      figmaName: component.name,
      iconNameKey,
      nodeId: component.node_id,
    });
  }

  mapped.sort((a, b) => a.figmaName.localeCompare(b.figmaName));

  const output = buildOutputFile(mapped);

  for (const outputPath of OUTPUT_PATHS) {
    await fs.writeFile(outputPath, output, 'utf8');
  }

  console.log(
    `Generated ${mapped.length} icon glyph connects (${unmapped.length} Figma glyphs skipped — no IconName match).`,
  );

  if (unmapped.length > 0) {
    console.log('Unmapped Figma glyphs:', unmapped.sort().join(', '));
  }
}

if (require.main === module) {
  main().catch((error: unknown) => {
    console.error(error);
    throw error;
  });
}
