import { transform } from '@svgr/core';
import jsxPlugin from '@svgr/plugin-jsx';
import svgoPlugin from '@svgr/plugin-svgo';
import * as fs from 'fs/promises';
import * as path from 'path';

// ─── Paths ────────────────────────────────────────────────────────────────────

const REPO_ROOT = path.join(__dirname, '../../..');

/** Single source of truth for all icon SVG assets */
const SHARED_ASSETS_DIR = path.join(__dirname, '../src/assets/icons');

/** Shared IconName const object lives here */
const SHARED_TYPES_FILE = path.join(
  __dirname,
  '../src/types/Icon/Icon.types.ts',
);

/** Sentinels that bracket the generated IconName block */
const ICON_NAME_SENTINEL_START =
  '// DO NOT EDIT - generated by generate-icons.ts';
const ICON_NAME_SENTINEL_END = '// END generated IconName';

// React Native paths
const RN_ASSETS_DIR = path.join(
  REPO_ROOT,
  'packages/design-system-react-native/src/components/Icon/assets',
);
const RN_ASSETS_FILE = path.join(
  REPO_ROOT,
  'packages/design-system-react-native/src/components/Icon/Icon.assets.ts',
);

// React paths
const REACT_ICONS_DIR = path.join(
  REPO_ROOT,
  'packages/design-system-react/src/components/Icon/icons',
);
const REACT_ICONS_INDEX_FILE = path.join(REACT_ICONS_DIR, 'index.ts');

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Converts a kebab-case SVG filename to a PascalCase icon name.
 * e.g. "add-card.svg" → "AddCard", "pop-up.svg" → "PopUp"
 *
 * @param fileName - The SVG filename to convert (e.g. "add-card.svg").
 * @returns The PascalCase icon name (e.g. "AddCard").
 */
function toPascalCase(fileName: string): string {
  return path
    .basename(fileName, '.svg')
    .split('-')
    .map((part) => `${part[0].toUpperCase()}${part.slice(1)}`)
    .join('');
}

/**
 * SVGR custom template — mirrors the existing React template.js so generated
 * components are identical in format to what was produced before centralisation.
 *
 * @param variables - The template variables provided by SVGR.
 * @param variables.componentName - The PascalCase component name (e.g. "SvgAddCard").
 * @param variables.jsx - The JSX markup generated from the SVG.
 * @param options1 - Additional SVGR template options.
 * @param options1.tpl - The tagged-template helper used to produce the output string.
 * @returns The complete TSX source string for the icon component.
 */
function svgrTemplate(
  variables: { componentName: string; jsx: string },
  { tpl }: { tpl: (...args: unknown[]) => string },
) {
  return tpl`
import type { SVGProps, Ref } from 'react';
import * as React from 'react';
import { forwardRef } from 'react';

const ${variables.componentName} = (
  props: SVGProps<SVGSVGElement>,
  ref: Ref<SVGSVGElement>,
) => (
  ${variables.jsx}
);

const ForwardRef = forwardRef(${variables.componentName});
export default ForwardRef;
`;
}

// ─── Step 1: Read & process SVG files ────────────────────────────────────────

async function readSvgFiles(): Promise<string[]> {
  const files = await fs.readdir(SHARED_ASSETS_DIR);
  return files.filter((f) => f.endsWith('.svg')).sort();
}

async function processSvgs(svgFiles: string[]): Promise<void> {
  for (const file of svgFiles) {
    const filePath = path.join(SHARED_ASSETS_DIR, file);
    const content = await fs.readFile(filePath, 'utf-8');
    // Replace hardcoded black fill with currentColor so icons inherit color
    const processed = content.replace(/black/gu, 'currentColor');
    await fs.writeFile(filePath, processed);
  }
}

// ─── Step 2: Update shared IconName ──────────────────────────────────────────

async function updateSharedIconName(svgFiles: string[]): Promise<void> {
  const typesContent = await fs.readFile(SHARED_TYPES_FILE, 'utf-8');

  const startIndex = typesContent.indexOf(ICON_NAME_SENTINEL_START);
  if (startIndex === -1) {
    throw new Error(
      `Start sentinel "${ICON_NAME_SENTINEL_START}" not found in ${SHARED_TYPES_FILE}.`,
    );
  }

  const endIndex = typesContent.indexOf(ICON_NAME_SENTINEL_END);
  if (endIndex === -1) {
    throw new Error(
      `End sentinel "${ICON_NAME_SENTINEL_END}" not found in ${SHARED_TYPES_FILE}.`,
    );
  }

  const beforeBlock = typesContent.slice(0, startIndex);
  // Preserve everything after the end sentinel line (including the sentinel itself)
  const afterBlockStart = typesContent.indexOf('\n', endIndex) + 1;
  const afterBlock = typesContent.slice(afterBlockStart);

  const iconEntries = svgFiles
    .map((file) => {
      const name = toPascalCase(file);
      return `  ${name}: '${name}',`;
    })
    .join('\n');

  const generatedBlock = [
    ICON_NAME_SENTINEL_START,
    `// /////////////////////////////////////////////////////`,
    ``,
    `/**`,
    ` * Icon - name`,
    ` * All icon names shared across React and React Native platforms.`,
    ` * This block is auto-generated — do not edit directly.`,
    ` * Run \`yarn generate:icons\` from the repo root to regenerate.`,
    ` */`,
    `export const IconName = {`,
    iconEntries,
    `} as const;`,
    ``,
    `export type IconName = (typeof IconName)[keyof typeof IconName];`,
    ``,
    ICON_NAME_SENTINEL_END,
    ``,
  ].join('\n');

  await fs.writeFile(
    SHARED_TYPES_FILE,
    beforeBlock + generatedBlock + afterBlock,
  );
}

// ─── Step 3: React Native — copy SVGs + generate Icon.assets.ts ──────────────

async function generateReactNativeAssets(svgFiles: string[]): Promise<void> {
  // Ensure RN assets directory exists
  await fs.mkdir(RN_ASSETS_DIR, { recursive: true });

  // Copy each processed SVG to RN assets folder
  for (const file of svgFiles) {
    const src = path.join(SHARED_ASSETS_DIR, file);
    const dest = path.join(RN_ASSETS_DIR, file);
    await fs.copyFile(src, dest);
  }

  // Generate Icon.assets.ts
  const lines: string[] = [
    `// /////////////////////////////////////////////////////`,
    `// This is a generated file`,
    `// DO NOT EDIT — run \`yarn generate:icons\` from the repo root`,
    `// /////////////////////////////////////////////////////`,
    `import { IconName } from '@metamask/design-system-shared';`,
    ``,
  ];

  for (const file of svgFiles) {
    const name = toPascalCase(file);
    lines.push(`import ${name}SVG from './assets/${file}';`);
  }

  lines.push(
    `import type { AssetByIconName } from './Icon.types';`,
    ``,
    `/**`,
    ` * Asset stored by icon name`,
    ` */`,
    `export const assetByIconName: AssetByIconName = {`,
  );

  for (const file of svgFiles) {
    const name = toPascalCase(file);
    lines.push(`  [IconName.${name}]: ${name}SVG,`);
  }

  lines.push(`};`, ``);

  await fs.writeFile(RN_ASSETS_FILE, lines.join('\n'));
}

// ─── Step 4: React — generate TSX components + icons/index.ts ────────────────

async function generateReactIcons(svgFiles: string[]): Promise<void> {
  // Ensure icons directory exists and clear previous output
  await fs.mkdir(REACT_ICONS_DIR, { recursive: true });
  const existing = await fs.readdir(REACT_ICONS_DIR);
  await Promise.all(existing.map((f) => fs.rm(path.join(REACT_ICONS_DIR, f))));

  const svgoConfig = {
    plugins: [
      {
        name: 'preset-default',
        params: {
          overrides: { removeViewBox: false },
        },
      },
      {
        name: 'addAttributesToSVGElement',
        params: {
          attributes: [{ fill: 'currentColor' }],
        },
      },
    ],
  };

  const iconNames: string[] = [];

  for (const file of svgFiles) {
    const pascalName = toPascalCase(file);
    const componentName = `Svg${pascalName}`;
    iconNames.push(pascalName);

    const svgContent = await fs.readFile(
      path.join(SHARED_ASSETS_DIR, file),
      'utf-8',
    );

    const tsxCode = await transform(
      svgContent,
      {
        plugins: [svgoPlugin, jsxPlugin],
        typescript: true,
        dimensions: false,
        ref: true,
        svgProps: { fill: 'currentColor' },
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        template: svgrTemplate as any,
        prettier: false,
        svgoConfig,
      },
      { componentName },
    );

    await fs.writeFile(
      path.join(REACT_ICONS_DIR, `${pascalName}.tsx`),
      tsxCode,
    );
  }

  // Generate icons/index.ts barrel export
  const indexLines: string[] = [
    `// This file is auto-generated — do not edit manually`,
    `// Run \`yarn generate:icons\` from the repo root to regenerate`,
    `import type { ForwardRefExoticComponent, RefAttributes, SVGProps } from 'react';`,
    ``,
    ...iconNames.map((name) => `import ${name} from './${name}';`),
    ``,
    `export const Icons = {`,
    ...iconNames.map((name) => `  ${name},`),
    `} as const;`,
    ``,
    `export type IconComponentType = ForwardRefExoticComponent<`,
    `  SVGProps<SVGSVGElement> & RefAttributes<SVGSVGElement>`,
    `>;`,
    ``,
    `export type IconsType = typeof Icons;`,
    ``,
  ];

  await fs.writeFile(REACT_ICONS_INDEX_FILE, indexLines.join('\n'));
}

// ─── Main ─────────────────────────────────────────────────────────────────────

export async function main(): Promise<void> {
  console.log('🎨 Generating icons...\n');

  const svgFiles = await readSvgFiles();
  console.log(`  Found ${svgFiles.length} SVG assets in shared package`);

  console.log('  Step 1/4: Processing SVGs (black → currentColor)...');
  await processSvgs(svgFiles);

  console.log('  Step 2/4: Updating shared IconName...');
  await updateSharedIconName(svgFiles);

  console.log('  Step 3/4: Generating React Native assets...');
  await generateReactNativeAssets(svgFiles);

  console.log('  Step 4/4: Generating React TSX components...');
  await generateReactIcons(svgFiles);

  console.log(`
✅ Done!
   • Shared:        ${SHARED_TYPES_FILE.replace(`${REPO_ROOT}/`, '')}
   • React Native:  ${RN_ASSETS_FILE.replace(`${REPO_ROOT}/`, '')} + ${svgFiles.length} SVG assets
   • React:         ${svgFiles.length} TSX components + icons/index.ts
`);
}

if (require.main === module) {
  main().catch((error: unknown) => {
    console.error(error);
    throw error;
  });
}
