// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import { IconSize } from '@metamask/design-system-shared';
import React from 'react';

import { IconAlert } from './IconAlert';

import { IconAlertSeverity } from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of IconAlert component
 */

figma.connect(
  IconAlert,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=4757-12584',
  {
    props: {
      severity: figma.enum('severity', {
        Info: IconAlertSeverity.Info,
        Success: IconAlertSeverity.Success,
        Warning: IconAlertSeverity.Warning,
        Danger: IconAlertSeverity.Danger,
      }),
      size: figma.enum('size', {
        Xs: IconSize.Xs,
        Sm: IconSize.Sm,
        Md: IconSize.Md,
        Lg: IconSize.Lg,
        Xl: IconSize.Xl,
      }),
    },
    example: ({ severity, size, ...props }) => (
      <IconAlert severity={severity} size={size} {...props} />
    ),
  },
);
