// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { AccountAvatar } from './AccountAvatar';
import { AccountAvatarSize } from './index';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of AccountAvatar component
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  AccountAvatar,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=128%3A1673',
  {
    props: {
      size: figma.enum('size', {
        Xs: AccountAvatarSize.Xs,
        Sm: AccountAvatarSize.Sm,
        Md: AccountAvatarSize.Md,
        Lg: AccountAvatarSize.Lg,
        Xl: AccountAvatarSize.Xl,
      }),
    },
    example: (props) => (
      <AccountAvatar
        address="0x9Cbf7c41B7787F6c621115010D3B044029FE2Ce8"
        {...props}
      />
    ),
  },
);
