// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { Icon, IconName, IconSize } from '../Icon';

import { BannerBase } from './BannerBase';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of BannerBase component.
 */

figma.connect(
  BannerBase,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=16610-20738',
  {
    props: {
      title: figma.string('title'),
      description: figma.string('description'),
      showStartAccessory: figma.boolean('startAccessory'),
      actionButton: figma.boolean('action', {
        true: figma.nestedProps('ButtonBase', {
          label: figma.string('label'),
        }),
        false: undefined,
      }),
      actionButtonOnPress: figma.boolean('action', {
        true: () => undefined,
        false: undefined,
      }),
      onClose: figma.boolean('endAccessory', {
        true: () => undefined,
        false: undefined,
      }),
      closeButtonProps: figma.boolean('endAccessory', {
        true: { testID: 'banner-base-close-button' },
        false: undefined,
      }),
    },
    example: ({
      title,
      description,
      showStartAccessory,
      actionButton,
      actionButtonOnPress,
      onClose,
      closeButtonProps,
    }) => (
      <BannerBase
        title={title}
        description={description}
        startAccessory={
          showStartAccessory ? (
            <Icon name={IconName.Info} size={IconSize.Lg} />
          ) : undefined
        }
        actionButtonLabel={actionButton?.label}
        actionButtonOnPress={actionButtonOnPress}
        onClose={onClose}
        closeButtonProps={closeButtonProps}
      />
    ),
  },
);
