// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { BannerBase } from './BannerBase';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of BannerBase component.
 *
 * Figma props: title/description (TEXT), action (BOOLEAN), startAccessory /
 * endAccessory (SLOT). Code exposes close via `onClose` (not an endAccessory
 * node), so close handlers match Storybook Default rather than the end SLOT.
 */

figma.connect(
  BannerBase,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=16610-20738',
  {
    props: {
      title: figma.string('title'),
      description: figma.string('description'),
      actionButton: figma.boolean('action', {
        true: figma.nestedProps('ButtonBase', {
          label: figma.string('label'),
        }),
        false: undefined,
      }),
      actionButtonOnPress: figma.boolean('action', {
        true: () => undefined,
        false: undefined,
      }),
      // Prefer children over figma.slot() so Dev Mode inlines the nested Icon
      // instead of emitting a nested StartAccessory() wrapper function.
      startAccessory: figma.children('startAccessory'),
    },
    example: ({
      title,
      description,
      actionButton,
      actionButtonOnPress,
      startAccessory,
    }) => (
      <BannerBase
        title={title}
        description={description}
        actionButtonLabel={actionButton?.label}
        actionButtonOnPress={actionButtonOnPress}
        onClose={() => undefined}
        closeButtonProps={{ testID: 'banner-base-close-button' }}
        startAccessory={startAccessory}
      />
    ),
  },
);
