// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { BottomSheetHeader } from './BottomSheetHeader';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of BottomSheetHeader component.
 *
 * Figma `startAccessory` / `endAccessory` map to `onBack` / `onClose`.
 * Providing those callbacks is what renders the back and close buttons in code.
 */

figma.connect(
  BottomSheetHeader,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=16572-21288',
  {
    props: {
      children: figma.string('title'),
      onBack: figma.boolean('startAccessory', {
        true: () => undefined,
        false: undefined,
      }),
      onClose: figma.boolean('endAccessory', {
        true: () => undefined,
        false: undefined,
      }),
    },
    example: ({ children, onBack, onClose }) => (
      <BottomSheetHeader onBack={onBack} onClose={onClose}>
        {children}
      </BottomSheetHeader>
    ),
  },
);
