// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { BottomSheetHeader } from './BottomSheetHeader';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of BottomSheetHeader component.
 */

figma.connect(
  BottomSheetHeader,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=16572-21288',
  {
    props: {
      title: figma.string('title'),
      startAccessory: figma.boolean('startAccessory'),
      endAccessory: figma.boolean('endAccessory'),
    },
    example: ({ title, startAccessory, endAccessory }) => {
      const handleBack = () => undefined;
      const handleClose = () => undefined;
      const onBack = startAccessory ? handleBack : undefined;
      const onClose = endAccessory ? handleClose : undefined;

      return (
        <BottomSheetHeader onBack={onBack} onClose={onClose}>
          {title}
        </BottomSheetHeader>
      );
    },
  },
);
