// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { AvatarToken } from './AvatarToken';

import { AvatarTokenSize } from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of AvatarToken component
 */

figma.connect(
  AvatarToken,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=128-2312',
  {
    props: {
      size: figma.enum('size', {
        Xs: AvatarTokenSize.Xs,
        Sm: AvatarTokenSize.Sm,
        Md: AvatarTokenSize.Md,
        Lg: AvatarTokenSize.Lg,
        Xl: AvatarTokenSize.Xl,
      }),
    },
    example: (props) => (
      <AvatarToken
        name="Ethereum"
        src={{ uri: './assets/token-icons/eth.svg' }}
        {...props}
      />
    ),
  },
);
