// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { BadgeNetwork } from './BadgeNetwork';

/**
 * -- This file was auto-generated by Code Connect --
 * React web implementation of BadgeNetwork component
 */

figma.connect(
  BadgeNetwork,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=580-4660',
  {
    example: () => (
      <BadgeNetwork name="Ethereum" src="./assets/network-icons/ethereum.svg" />
    ),
  },
);
