// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { BadgeNetwork } from './BadgeNetwork';

/**
 * -- This file was auto-generated by Code Connect --
 * React web implementation of BadgeNetwork component
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  BadgeNetwork,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-WIP--MMDS-Components?node-id=580%3A4660',
  {
    props: {},
    example: (props) => (
      <BadgeNetwork
        name="Ethereum"
        src="./assets/network-icons/ethereum.svg"
        {...props}
      />
    ),
  },
);
