// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { Textarea } from './Textarea';

import { TextareaResize } from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React web implementation of Textarea component
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Textarea,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-WIP--MMDS-Components?node-id=12091%3A104',
  {
    props: {
      isDisabled: figma.boolean('isDisabled'),
      isError: figma.boolean('isError'),
      isReadOnly: figma.boolean('isReadOnly'),
      resize: figma.enum('resize', {
        Vertical: TextareaResize.Vertical,
        Horizontal: TextareaResize.Horizontal,
        Both: TextareaResize.Both,
        None: TextareaResize.None,
      }),
      placeholder: figma.string('placeholder'),
    },
    example: ({ isDisabled, isError, isReadOnly, resize, placeholder }) => (
      <Textarea
        isDisabled={isDisabled}
        isError={isError}
        isReadOnly={isReadOnly}
        resize={resize}
        placeholder={placeholder ?? 'Enter text'}
      />
    ),
  },
);
