// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { AvatarAccount } from './AvatarAccount';

import { AvatarAccountSize, AvatarAccountVariant } from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React web implementation of AvatarAccount component
 */

figma.connect(
  AvatarAccount,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=9519-1552',
  {
    props: {
      size: figma.enum('size', {
        Xs: AvatarAccountSize.Xs,
        Sm: AvatarAccountSize.Sm,
        Md: AvatarAccountSize.Md,
        Lg: AvatarAccountSize.Lg,
        Xl: AvatarAccountSize.Xl,
      }),
      variant: figma.enum('variant', {
        blockies: AvatarAccountVariant.Blockies,
        jazzicon: AvatarAccountVariant.Jazzicon,
        polycon: AvatarAccountVariant.Maskicon,
      }),
    },
    example: (props) => (
      <AvatarAccount
        address="0x9Cbf7c41B7787F6c621115010D3B044029FE2Ce8"
        {...props}
      />
    ),
  },
);
