// import figma needs to remain as figma otherwise it breaks code connect
/* eslint-disable import-x/no-named-as-default */
import figma from '@figma/code-connect';
import React from 'react';

import { AvatarAccount } from './AvatarAccount';

import { AvatarAccountSize } from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React web implementation of AvatarAccount component
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  AvatarAccount,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-WIP--MMDS-Components?node-id=128%3A1673',
  {
    props: {
      size: figma.enum('size', {
        Xs: AvatarAccountSize.Xs,
        Sm: AvatarAccountSize.Sm,
        Md: AvatarAccountSize.Md,
        Lg: AvatarAccountSize.Lg,
        Xl: AvatarAccountSize.Xl,
      }),
    },
    example: (props) => (
      <AvatarAccount
        address="0x9Cbf7c41B7787F6c621115010D3B044029FE2Ce8"
        {...props}
      />
    ),
  },
);
