// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { SelectButton } from './SelectButton';

import {
  SelectButtonEndArrow,
  SelectButtonSize,
  SelectButtonVariant,
} from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of SelectButton component.
 */

figma.connect(
  SelectButton,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=13719-742',
  {
    props: {
      variant: figma.enum('variant', {
        Primary: SelectButtonVariant.Primary,
        Secondary: SelectButtonVariant.Secondary,
        Tertiary: SelectButtonVariant.Tertiary,
      }),
      size: figma.enum('size', {
        Lg: SelectButtonSize.Lg,
        Md: SelectButtonSize.Md,
        Sm: SelectButtonSize.Sm,
      }),
      isDisabled: figma.enum('isDisabled', {
        true: true,
        false: undefined,
      }),
      buttonBase: figma.nestedProps('ButtonBase', {
        placeholder: figma.string('label'),
      }),
    },
    example: ({ variant, size, isDisabled, buttonBase }) => (
      <SelectButton
        placeholder={buttonBase.placeholder}
        variant={variant}
        size={size}
        endArrowDirection={SelectButtonEndArrow.Down}
        isDisabled={isDisabled}
        onPress={() => undefined}
      />
    ),
  },
);
