// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { Card } from './Card';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of Card component.
 *
 * Root Figma props: `children` (SLOT). Property names must match Dev Mode exactly.
 *
 * - **`children`** maps the Figma SLOT of the same name via
 *   `figma.slot('children').connectedInstances`. Dropping code-connected
 *   components into the slot updates the snippet. The default Placeholder
 *   frame and text layer are not code-connected, so the slot renders empty
 *   until content is added — matching Storybook Default (`<Card>{children}</Card>`).
 * - **`onPress`**, **`twClassName`**, **`touchableOpacityProps`** and **`style`**
 *   are code-only; Figma has no matching properties, so they are omitted rather
 *   than hardcoded into every snippet.
 */

figma.connect(
  Card,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=19265-3',
  {
    props: {
      children: figma.slot('children').connectedInstances,
    },
    example: ({ children }) => (
      <Card>
        {/* Add your custom content here */}
        {children}
      </Card>
    ),
  },
);
