// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { IconName } from '../Icon';

import { ButtonHero } from './ButtonHero';

import { ButtonHeroSize } from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of ButtonHero component
 */

figma.connect(
  ButtonHero,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=9309-7848',
  {
    props: {
      size: figma.nestedProps('ButtonBase', {
        value: figma.enum('size', {
          Lg: undefined,
          Md: ButtonHeroSize.Md,
          Sm: ButtonHeroSize.Sm,
        }),
      }).value,
      children: figma.nestedProps('ButtonBase', {
        value: figma.string('label'),
      }).value,
      startIconName: figma.nestedProps('ButtonBase', {
        value: figma.boolean('startIcon (Figma Only)', {
          true: IconName.Add,
          false: undefined,
        }),
      }).value,
      endIconName: figma.nestedProps('ButtonBase', {
        value: figma.boolean('endIcon (Figma Only)', {
          true: IconName.Add,
          false: undefined,
        }),
      }).value,
      loadingText: figma.nestedProps('_Loading Label', {
        value: figma.boolean('show loadingText', {
          true: figma.string('loadingText'),
          false: undefined,
        }),
      }).value,
      isLoading: figma.boolean('isLoading', {
        true: true,
        false: undefined,
      }),
      isDisabled: figma.boolean('isDisabled', {
        true: true,
        false: undefined,
      }),
    },
    example: ({
      size,
      children,
      startIconName,
      endIconName,
      loadingText,
      isLoading,
      isDisabled,
    }) => (
      <ButtonHero
        size={size}
        startIconName={startIconName}
        endIconName={endIconName}
        isLoading={isLoading}
        loadingText={loadingText}
        isDisabled={isDisabled}
      >
        {children}
      </ButtonHero>
    ),
  },
);
