// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { IconName } from '../Icon';

import { ButtonIcon } from './ButtonIcon';

import { ButtonIconSize } from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of ButtonIcon component
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ButtonIcon,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-WIP--MMDS-Components?node-id=1%3A2860',
  {
    props: {
      size: figma.enum('size', {
        Sm: ButtonIconSize.Sm,
        Md: ButtonIconSize.Md,
        Lg: ButtonIconSize.Lg,
      }),
      isDisabled: figma.boolean('isDisabled'),
      isInverse: figma.boolean('isInverse'),
      isFloating: figma.boolean('isFloating'),
    },
    example: ({ size, isDisabled, isInverse, isFloating, ...props }) => (
      <ButtonIcon
        size={size}
        iconName={IconName.Close} // Check the icon name in figma
        accessibilityLabel="Close" // Describe action. Required accessibility prop
        isDisabled={isDisabled}
        isInverse={isInverse}
        isFloating={isFloating}
        {...props}
      />
    ),
  },
);
