// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import {
  ButtonBaseSize,
  FilterButtonVariant,
} from '@metamask/design-system-shared';
import React from 'react';

import { IconName } from '../Icon';

import { FilterButton } from './FilterButton';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of FilterButton component.
 */

figma.connect(
  FilterButton,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=16475-25833',
  {
    props: {
      variant: figma.enum('variant', {
        primary: FilterButtonVariant.Primary,
        secondary: FilterButtonVariant.Secondary,
      }),
      isSelected: figma.boolean('isSelected', {
        true: true,
        false: false,
      }),
      size: figma.enum('size', {
        Lg: ButtonBaseSize.Lg,
        Md: ButtonBaseSize.Md,
        Sm: ButtonBaseSize.Sm,
      }),
      buttonBase: figma.nestedProps('_ButtonBase', {
        label: figma.string('label'),
        startIconName: figma.boolean('startIcon (Figma Only)', {
          true: IconName.Add,
          false: undefined,
        }),
        endIconName: figma.boolean('endIcon (Figma Only)', {
          true: IconName.Add,
          false: undefined,
        }),
      }),
    },
    example: ({ variant, isSelected, size, buttonBase }) => (
      <FilterButton
        variant={variant}
        isSelected={isSelected}
        size={size}
        startIconName={buttonBase.startIconName}
        endIconName={buttonBase.endIconName}
        onPress={() => undefined}
      >
        {buttonBase.label}
      </FilterButton>
    ),
  },
);
