// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { BannerBase } from './BannerBase';

/* -- This file was auto-generated by Code Connect -- */
figma.connect(
  BannerBase,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=16610-20738',
  {
    props: {
      title: figma.string('title'),
      description: figma.string('description'),
      startAccessory: figma.boolean('startAccessory', {
        true: figma.children('startAccessory'),
        false: undefined,
      }),
      actionButton: figma.nestedProps('ButtonBase', {
        label: figma.string('label'),
      }),
      hasAction: figma.boolean('action'),
      hasClose: figma.boolean('endAccessory'),
    },
    example: ({
      title,
      description,
      startAccessory,
      actionButton,
      hasAction,
      hasClose,
    }) => {
      const bannerProps: React.ComponentProps<typeof BannerBase> = {
        title,
        description,
        startAccessory,
      };

      if (hasAction && actionButton?.label) {
        bannerProps.actionButtonLabel = actionButton.label;
        bannerProps.actionButtonOnClick = () => undefined;
      }

      if (hasClose) {
        bannerProps.onClose = () => undefined;
      }

      return <BannerBase {...bannerProps} />;
    },
  },
);
