// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { BannerBase } from './BannerBase';

/**
 * -- This file was auto-generated by Code Connect --
 * React web implementation of BannerBase component.
 *
 * Figma props: title/description (TEXT), action (BOOLEAN), startAccessory /
 * endAccessory (SLOT). `onClose` is gated on the `close` boolean property
 * (bound to the endAccessory layer's visibility in Figma).
 */

figma.connect(
  BannerBase,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=16610-20738',
  {
    props: {
      title: figma.string('title'),
      description: figma.string('description'),
      // false fallback keeps `.label` safe without optional chaining (parser rejects `?.`)
      actionButton: figma.boolean('action', {
        true: figma.nestedProps('ButtonBase', {
          label: figma.string('label'),
        }),
        false: { label: undefined },
      }),
      actionButtonOnClick: figma.boolean('action', {
        true: () => undefined,
        false: undefined,
      }),
      onClose: figma.boolean('close', {
        true: () => undefined,
        false: undefined,
      }),
      closeButtonProps: figma.boolean('close', {
        true: { 'data-testid': 'banner-base-close-button' },
        false: undefined,
      }),
      startAccessory: figma.slot('startAccessory').connectedInstances,
    },
    example: ({
      title,
      description,
      actionButton,
      actionButtonOnClick,
      onClose,
      closeButtonProps,
      startAccessory,
    }) => (
      <BannerBase
        title={title}
        description={description}
        actionButtonLabel={actionButton.label}
        actionButtonOnClick={actionButtonOnClick}
        onClose={onClose}
        closeButtonProps={closeButtonProps}
        startAccessory={startAccessory}
      />
    ),
  },
);
