// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { HeaderStandard } from './HeaderStandard';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of HeaderStandard component.
 */

figma.connect(
  HeaderStandard,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/branch/w2n6gtbyemD7VTNoACgrqm/%F0%9F%A6%8A-MMDS-Components?node-id=15712-763',
  {
    props: {
      title: figma.string('title'),
      subtitle: figma.string('subtitle'),
      startAccessory: figma.slot('startAccessory'),
      endAccessory: figma.slot('endAccessory'),
    },
    example: ({ title, subtitle, startAccessory, endAccessory }) => (
      <HeaderStandard
        title={title}
        subtitle={subtitle}
        startAccessory={startAccessory}
        endAccessory={endAccessory}
      />
    ),
  },
);
