// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { HeaderBase } from './HeaderBase';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of HeaderBase.
 *
 * Figma props: `title` (TEXT), `startAccessory` / `endAccessory` (SLOT).
 * Nested ButtonIcon instances in those slots surface via Code Connect when
 * the nested component is published. String `children` matches Storybook
 * Default (`TextOrChildren` renders the title). Code-only props
 * (`startButtonIconProps`, `endButtonIconProps`, `includesTopInset`,
 * wrapper props, `twClassName`) are omitted.
 */

figma.connect(
  HeaderBase,
  'https://www.figma.com/design/gb5bUp62vu1DkL0fCBDaOo/refactor--Header?node-id=19284-754',
  {
    props: {
      children: figma.string('title'),
      startAccessory: figma.slot('startAccessory').connectedInstances,
      endAccessory: figma.slot('endAccessory').connectedInstances,
    },
    example: ({ children, startAccessory, endAccessory }) => (
      <HeaderBase startAccessory={startAccessory} endAccessory={endAccessory}>
        {children}
      </HeaderBase>
    ),
  },
);
