import type { BoxSpacing } from '../../types';
import { BoxBlockSize } from '../../types';

export const TWCLASSMAP_BOX_GAP: Record<BoxSpacing, string> = {
  0: 'gap-0',
  1: 'gap-1',
  2: 'gap-2',
  3: 'gap-3',
  4: 'gap-4',
  5: 'gap-5',
  6: 'gap-6',
  7: 'gap-7',
  8: 'gap-8',
  9: 'gap-9',
  10: 'gap-10',
  11: 'gap-11',
  12: 'gap-12',
};

export const TWCLASSMAP_BOX_MARGIN: Record<BoxSpacing, string> = {
  0: 'm-0',
  1: 'm-1',
  2: 'm-2',
  3: 'm-3',
  4: 'm-4',
  5: 'm-5',
  6: 'm-6',
  7: 'm-7',
  8: 'm-8',
  9: 'm-9',
  10: 'm-10',
  11: 'm-11',
  12: 'm-12',
};

export const TWCLASSMAP_BOX_MARGINTOP: Record<BoxSpacing, string> = {
  0: 'mt-0',
  1: 'mt-1',
  2: 'mt-2',
  3: 'mt-3',
  4: 'mt-4',
  5: 'mt-5',
  6: 'mt-6',
  7: 'mt-7',
  8: 'mt-8',
  9: 'mt-9',
  10: 'mt-10',
  11: 'mt-11',
  12: 'mt-12',
};

export const TWCLASSMAP_BOX_MARGINBOTTOM: Record<BoxSpacing, string> = {
  0: 'mb-0',
  1: 'mb-1',
  2: 'mb-2',
  3: 'mb-3',
  4: 'mb-4',
  5: 'mb-5',
  6: 'mb-6',
  7: 'mb-7',
  8: 'mb-8',
  9: 'mb-9',
  10: 'mb-10',
  11: 'mb-11',
  12: 'mb-12',
};

export const TWCLASSMAP_BOX_MARGINLEFT: Record<BoxSpacing, string> = {
  0: 'ml-0',
  1: 'ml-1',
  2: 'ml-2',
  3: 'ml-3',
  4: 'ml-4',
  5: 'ml-5',
  6: 'ml-6',
  7: 'ml-7',
  8: 'ml-8',
  9: 'ml-9',
  10: 'ml-10',
  11: 'ml-11',
  12: 'ml-12',
};

export const TWCLASSMAP_BOX_MARGINRIGHT: Record<BoxSpacing, string> = {
  0: 'mr-0',
  1: 'mr-1',
  2: 'mr-2',
  3: 'mr-3',
  4: 'mr-4',
  5: 'mr-5',
  6: 'mr-6',
  7: 'mr-7',
  8: 'mr-8',
  9: 'mr-9',
  10: 'mr-10',
  11: 'mr-11',
  12: 'mr-12',
};

export const TWCLASSMAP_BOX_PADDING: Record<BoxSpacing, string> = {
  0: 'p-0',
  1: 'p-1',
  2: 'p-2',
  3: 'p-3',
  4: 'p-4',
  5: 'p-5',
  6: 'p-6',
  7: 'p-7',
  8: 'p-8',
  9: 'p-9',
  10: 'p-10',
  11: 'p-11',
  12: 'p-12',
};

export const TWCLASSMAP_BOX_PADDINGTOP: Record<BoxSpacing, string> = {
  0: 'pt-0',
  1: 'pt-1',
  2: 'pt-2',
  3: 'pt-3',
  4: 'pt-4',
  5: 'pt-5',
  6: 'pt-6',
  7: 'pt-7',
  8: 'pt-8',
  9: 'pt-9',
  10: 'pt-10',
  11: 'pt-11',
  12: 'pt-12',
};

export const TWCLASSMAP_BOX_PADDINGBOTTOM: Record<BoxSpacing, string> = {
  0: 'pb-0',
  1: 'pb-1',
  2: 'pb-2',
  3: 'pb-3',
  4: 'pb-4',
  5: 'pb-5',
  6: 'pb-6',
  7: 'pb-7',
  8: 'pb-8',
  9: 'pb-9',
  10: 'pb-10',
  11: 'pb-11',
  12: 'pb-12',
};

export const TWCLASSMAP_BOX_PADDINGLEFT: Record<BoxSpacing, string> = {
  0: 'pl-0',
  1: 'pl-1',
  2: 'pl-2',
  3: 'pl-3',
  4: 'pl-4',
  5: 'pl-5',
  6: 'pl-6',
  7: 'pl-7',
  8: 'pl-8',
  9: 'pl-9',
  10: 'pl-10',
  11: 'pl-11',
  12: 'pl-12',
};

export const TWCLASSMAP_BOX_PADDINGRIGHT: Record<BoxSpacing, string> = {
  0: 'pr-0',
  1: 'pr-1',
  2: 'pr-2',
  3: 'pr-3',
  4: 'pr-4',
  5: 'pr-5',
  6: 'pr-6',
  7: 'pr-7',
  8: 'pr-8',
  9: 'pr-9',
  10: 'pr-10',
  11: 'pr-11',
  12: 'pr-12',
};

export const TWCLASSMAP_BOX_WIDTH: Record<BoxBlockSize, string> = {
  [BoxBlockSize.Zero]: 'w-0',
  [BoxBlockSize.Half]: 'w-1/2',
  [BoxBlockSize.OneThird]: 'w-1/3',
  [BoxBlockSize.TwoThirds]: 'w-2/3',
  [BoxBlockSize.OneFourth]: 'w-1/4',
  [BoxBlockSize.ThreeFourths]: 'w-3/4',
  [BoxBlockSize.OneFifth]: 'w-1/5',
  [BoxBlockSize.TwoFifths]: 'w-2/5',
  [BoxBlockSize.ThreeFifths]: 'w-3/5',
  [BoxBlockSize.FourFifths]: 'w-4/5',
  [BoxBlockSize.OneSixth]: 'w-1/6',
  [BoxBlockSize.FiveSixths]: 'w-5/6',
  [BoxBlockSize.OneTwelfth]: 'w-1/12',
  [BoxBlockSize.TwoTwelfths]: 'w-2/12',
  [BoxBlockSize.ThreeTwelfths]: 'w-3/12',
  [BoxBlockSize.FourTwelfths]: 'w-4/12',
  [BoxBlockSize.FiveTwelfths]: 'w-5/12',
  [BoxBlockSize.SixTwelfths]: 'w-6/12',
  [BoxBlockSize.SevenTwelfths]: 'w-7/12',
  [BoxBlockSize.EightTwelfths]: 'w-8/12',
  [BoxBlockSize.NineTwelfths]: 'w-9/12',
  [BoxBlockSize.TenTwelfths]: 'w-10/12',
  [BoxBlockSize.ElevenTwelfths]: 'w-11/12',
  [BoxBlockSize.Full]: 'w-full',
  [BoxBlockSize.Screen]: 'w-screen',
  [BoxBlockSize.Auto]: 'w-auto',
  [BoxBlockSize.Min]: 'w-min',
  [BoxBlockSize.Max]: 'w-max',
};

export const TWCLASSMAP_BOX_MINWIDTH: Record<BoxBlockSize, string> = {
  [BoxBlockSize.Zero]: 'min-w-0',
  [BoxBlockSize.Half]: 'min-w-1/2',
  [BoxBlockSize.OneThird]: 'min-w-1/3',
  [BoxBlockSize.TwoThirds]: 'min-w-2/3',
  [BoxBlockSize.OneFourth]: 'min-w-1/4',
  [BoxBlockSize.ThreeFourths]: 'min-w-3/4',
  [BoxBlockSize.OneFifth]: 'min-w-1/5',
  [BoxBlockSize.TwoFifths]: 'min-w-2/5',
  [BoxBlockSize.ThreeFifths]: 'min-w-3/5',
  [BoxBlockSize.FourFifths]: 'min-w-4/5',
  [BoxBlockSize.OneSixth]: 'min-w-1/6',
  [BoxBlockSize.FiveSixths]: 'min-w-5/6',
  [BoxBlockSize.OneTwelfth]: 'min-w-1/12',
  [BoxBlockSize.TwoTwelfths]: 'min-w-2/12',
  [BoxBlockSize.ThreeTwelfths]: 'min-w-3/12',
  [BoxBlockSize.FourTwelfths]: 'min-w-4/12',
  [BoxBlockSize.FiveTwelfths]: 'min-w-5/12',
  [BoxBlockSize.SixTwelfths]: 'min-w-6/12',
  [BoxBlockSize.SevenTwelfths]: 'min-w-7/12',
  [BoxBlockSize.EightTwelfths]: 'min-w-8/12',
  [BoxBlockSize.NineTwelfths]: 'min-w-9/12',
  [BoxBlockSize.TenTwelfths]: 'min-w-10/12',
  [BoxBlockSize.ElevenTwelfths]: 'min-w-11/12',
  [BoxBlockSize.Full]: 'min-w-full',
  [BoxBlockSize.Screen]: 'min-w-screen',
  [BoxBlockSize.Auto]: 'min-w-auto',
  [BoxBlockSize.Min]: 'min-w-min',
  [BoxBlockSize.Max]: 'min-w-max',
};

export const TWCLASSMAP_BOX_HEIGHT: Record<BoxBlockSize, string> = {
  [BoxBlockSize.Zero]: 'h-0',
  [BoxBlockSize.Half]: 'h-1/2',
  [BoxBlockSize.OneThird]: 'h-1/3',
  [BoxBlockSize.TwoThirds]: 'h-2/3',
  [BoxBlockSize.OneFourth]: 'h-1/4',
  [BoxBlockSize.ThreeFourths]: 'h-3/4',
  [BoxBlockSize.OneFifth]: 'h-1/5',
  [BoxBlockSize.TwoFifths]: 'h-2/5',
  [BoxBlockSize.ThreeFifths]: 'h-3/5',
  [BoxBlockSize.FourFifths]: 'h-4/5',
  [BoxBlockSize.OneSixth]: 'h-1/6',
  [BoxBlockSize.FiveSixths]: 'h-5/6',
  [BoxBlockSize.OneTwelfth]: 'h-1/12',
  [BoxBlockSize.TwoTwelfths]: 'h-2/12',
  [BoxBlockSize.ThreeTwelfths]: 'h-3/12',
  [BoxBlockSize.FourTwelfths]: 'h-4/12',
  [BoxBlockSize.FiveTwelfths]: 'h-5/12',
  [BoxBlockSize.SixTwelfths]: 'h-6/12',
  [BoxBlockSize.SevenTwelfths]: 'h-7/12',
  [BoxBlockSize.EightTwelfths]: 'h-8/12',
  [BoxBlockSize.NineTwelfths]: 'h-9/12',
  [BoxBlockSize.TenTwelfths]: 'h-10/12',
  [BoxBlockSize.ElevenTwelfths]: 'h-11/12',
  [BoxBlockSize.Full]: 'h-full',
  [BoxBlockSize.Screen]: 'h-screen',
  [BoxBlockSize.Auto]: 'h-auto',
  [BoxBlockSize.Min]: 'h-min',
  [BoxBlockSize.Max]: 'h-max',
};

export const TWCLASSMAP_BOX_MINHEIGHT: Record<BoxBlockSize, string> = {
  [BoxBlockSize.Zero]: 'min-h-0',
  [BoxBlockSize.Half]: 'min-h-1/2',
  [BoxBlockSize.OneThird]: 'min-h-1/3',
  [BoxBlockSize.TwoThirds]: 'min-h-2/3',
  [BoxBlockSize.OneFourth]: 'min-h-1/4',
  [BoxBlockSize.ThreeFourths]: 'min-h-3/4',
  [BoxBlockSize.OneFifth]: 'min-h-1/5',
  [BoxBlockSize.TwoFifths]: 'min-h-2/5',
  [BoxBlockSize.ThreeFifths]: 'min-h-3/5',
  [BoxBlockSize.FourFifths]: 'min-h-4/5',
  [BoxBlockSize.OneSixth]: 'min-h-1/6',
  [BoxBlockSize.FiveSixths]: 'min-h-5/6',
  [BoxBlockSize.OneTwelfth]: 'min-h-1/12',
  [BoxBlockSize.TwoTwelfths]: 'min-h-2/12',
  [BoxBlockSize.ThreeTwelfths]: 'min-h-3/12',
  [BoxBlockSize.FourTwelfths]: 'min-h-4/12',
  [BoxBlockSize.FiveTwelfths]: 'min-h-5/12',
  [BoxBlockSize.SixTwelfths]: 'min-h-6/12',
  [BoxBlockSize.SevenTwelfths]: 'min-h-7/12',
  [BoxBlockSize.EightTwelfths]: 'min-h-8/12',
  [BoxBlockSize.NineTwelfths]: 'min-h-9/12',
  [BoxBlockSize.TenTwelfths]: 'min-h-10/12',
  [BoxBlockSize.ElevenTwelfths]: 'min-h-11/12',
  [BoxBlockSize.Full]: 'min-h-full',
  [BoxBlockSize.Screen]: 'min-h-screen',
  [BoxBlockSize.Auto]: 'min-h-auto',
  [BoxBlockSize.Min]: 'min-h-min',
  [BoxBlockSize.Max]: 'min-h-max',
};
