// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { IconName } from '../Icon';

import { ButtonSemantic } from './ButtonSemantic';

import { ButtonSemanticSeverity, ButtonSemanticSize } from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of ButtonSemantic component
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ButtonSemantic,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=19259-2949',
  {
    props: {
      severity: figma.enum('severity', {
        Success: ButtonSemanticSeverity.Success,
        Danger: ButtonSemanticSeverity.Danger,
      }),
      buttonBase: figma.nestedProps('ButtonBase', {
        size: figma.enum('size', {
          Sm: ButtonSemanticSize.Sm,
          Md: ButtonSemanticSize.Md,
          Lg: ButtonSemanticSize.Lg,
        }),
        label: figma.string('label'),
        startIconName: figma.boolean('startIcon (Figma Only)', {
          true: IconName.Add,
          false: undefined,
        }),
        endIconName: figma.boolean('endIcon (Figma Only)', {
          true: IconName.Add,
          false: undefined,
        }),
      }),
      loadingText: figma.nestedProps('_Loading Label', {
        text: figma.boolean('show loadingText', {
          true: figma.string('loadingText'),
          false: undefined,
        }),
      }),
      isFullWidth: figma.boolean('isFullWidth', {
        true: true,
        false: undefined,
      }),
      isLoading: figma.boolean('isLoading', {
        true: true,
        false: undefined,
      }),
      isDisabled: figma.boolean('isDisabled', {
        true: true,
        false: undefined,
      }),
    },
    example: ({
      severity,
      buttonBase,
      isFullWidth,
      isLoading,
      isDisabled,
      loadingText,
    }) => (
      <ButtonSemantic
        severity={severity}
        size={buttonBase.size}
        isFullWidth={isFullWidth}
        isLoading={isLoading}
        loadingText={loadingText.text}
        isDisabled={isDisabled}
        startIconName={buttonBase.startIconName}
        endIconName={buttonBase.endIconName}
        onPress={() => undefined}
      >
        {buttonBase.label}
      </ButtonSemantic>
    ),
  },
);
