// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { Text, TextColor, TextVariant } from '../Text';

import { HeaderBase } from './HeaderBase';

/**
 * -- This file was auto-generated by Code Connect --
 * React web implementation of HeaderBase.
 *
 * Figma props: `title` / `subtitle` (TEXT), `startAccessory` / `endAccessory`
 * (SLOT), `hasSubtitle (Figma only)` (BOOLEAN). HeaderBase has no subtitle
 * prop — when the Figma toggle is on, title and subtitle are composed as
 * `children`. The Figma-only toggle is selected via `variant` so it never
 * appears in the snippet. Nested ButtonIcon instances in the slots surface
 * via Code Connect when the nested component is published. Code-only wrapper
 * props (`className`, `*WrapperProps`) are omitted.
 */

const HEADER_BASE_URL =
  'https://www.figma.com/design/gb5bUp62vu1DkL0fCBDaOo/refactor--Header?node-id=19284-754';

figma.connect(HeaderBase, HEADER_BASE_URL, {
  variant: { 'hasSubtitle (Figma only)': false },
  props: {
    children: figma.string('title'),
    startAccessory: figma.slot('startAccessory').connectedInstances,
    endAccessory: figma.slot('endAccessory').connectedInstances,
  },
  example: ({ children, startAccessory, endAccessory }) => (
    <HeaderBase startAccessory={startAccessory} endAccessory={endAccessory}>
      <Text variant={TextVariant.HeadingSm}>{children}</Text>
    </HeaderBase>
  ),
});

figma.connect(HeaderBase, HEADER_BASE_URL, {
  variant: { 'hasSubtitle (Figma only)': true },
  props: {
    children: figma.string('title'),
    subtitle: figma.string('subtitle'),
    startAccessory: figma.slot('startAccessory').connectedInstances,
    endAccessory: figma.slot('endAccessory').connectedInstances,
  },
  example: ({ children, subtitle, startAccessory, endAccessory }) => (
    <HeaderBase startAccessory={startAccessory} endAccessory={endAccessory}>
      <Text variant={TextVariant.HeadingSm}>{children}</Text>
      <Text variant={TextVariant.BodySm} color={TextColor.TextAlternative}>
        {subtitle}
      </Text>
    </HeaderBase>
  ),
});
