// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { IconName } from '../Icon';

import { ButtonHero } from './ButtonHero';

import { ButtonHeroSize } from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React web implementation of ButtonHero component
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ButtonHero,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=19259-2861',
  {
    props: {
      buttonBase: figma.nestedProps('ButtonBase', {
        size: figma.enum('size', {
          Lg: ButtonHeroSize.Lg,
          Md: ButtonHeroSize.Md,
          Sm: ButtonHeroSize.Sm,
        }),
        label: figma.string('label'),
        startIconName: figma.boolean('startIcon (Figma Only)', {
          true: IconName.Add,
          false: undefined,
        }),
        endIconName: figma.boolean('endIcon (Figma Only)', {
          true: IconName.Add,
          false: undefined,
        }),
      }),
      loadingText: figma.nestedProps('_Loading Label', {
        text: figma.boolean('show loadingText', {
          true: figma.string('loadingText'),
          false: undefined,
        }),
      }),
      isLoading: figma.boolean('isLoading', {
        true: true,
        false: undefined,
      }),
      isDisabled: figma.boolean('isDisabled', {
        true: true,
        false: undefined,
      }),
    },
    example: ({ buttonBase, loadingText, isLoading, isDisabled }) => (
      <ButtonHero
        size={buttonBase.size}
        startIconName={buttonBase.startIconName}
        endIconName={buttonBase.endIconName}
        isLoading={isLoading}
        loadingText={loadingText.text}
        isDisabled={isDisabled}
      >
        {buttonBase.label}
      </ButtonHero>
    ),
  },
);
