// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { BadgeCount } from './BadgeCount';

import { BadgeCountSize } from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React web implementation of BadgeCount component
 */

figma.connect(
  BadgeCount,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=623-3506',
  {
    props: {
      size: figma.enum('size', {
        Md: BadgeCountSize.Md,
        Lg: BadgeCountSize.Lg,
      }),
    },
    example: (props) => <BadgeCount count={8} {...props} />,
  },
);
