export const colors = {
  background: {
    default: 'var(--mm-color-background-default)',
    'default-hover': 'var(--mm-color-background-default-hover)',
    'default-pressed': 'var(--mm-color-background-default-pressed)',
    alternative: 'var(--mm-color-background-alternative)',
    'alternative-hover': 'var(--mm-color-background-alternative-hover)',
    'alternative-pressed': 'var(--mm-color-background-alternative-pressed)',
    section: 'var(--mm-color-background-section)',
    subsection: 'var(--mm-color-background-subsection)',
    muted: 'var(--mm-color-background-muted)',
    'muted-hover': 'var(--mm-color-background-muted-hover)',
    'muted-pressed': 'var(--mm-color-background-muted-pressed)',
    hover: 'var(--mm-color-background-hover)',
    pressed: 'var(--mm-color-background-pressed)',
  },
  text: {
    default: 'var(--mm-color-text-default)',
    alternative: 'var(--mm-color-text-alternative)',
    muted: 'var(--mm-color-text-muted)',
  },
  border: {
    default: 'var(--mm-color-border-default)',
    muted: 'var(--mm-color-border-muted)',
  },
  icon: {
    default: 'var(--mm-color-icon-default)',
    'default-hover': 'var(--mm-color-icon-default-hover)',
    'default-pressed': 'var(--mm-color-icon-default-pressed)',
    alternative: 'var(--mm-color-icon-alternative)',
    muted: 'var(--mm-color-icon-muted)',
    inverse: 'var(--mm-color-icon-inverse)',
  },
  overlay: {
    default: 'var(--mm-color-overlay-default)',
    alternative: 'var(--mm-color-overlay-alternative)',
    inverse: 'var(--mm-color-overlay-inverse)',
  },
  primary: {
    default: 'var(--mm-color-primary-default)',
    'default-hover': 'var(--mm-color-primary-default-hover)',
    'default-pressed': 'var(--mm-color-primary-default-pressed)',
    alternative: 'var(--mm-color-primary-alternative)',
    muted: 'var(--mm-color-primary-muted)',
    inverse: 'var(--mm-color-primary-inverse)',
    'muted-hover': 'var(--mm-color-primary-muted-hover)',
    'muted-pressed': 'var(--mm-color-primary-muted-pressed)',
  },
  error: {
    default: 'var(--mm-color-error-default)',
    'default-hover': 'var(--mm-color-error-default-hover)',
    'default-pressed': 'var(--mm-color-error-default-pressed)',
    alternative: 'var(--mm-color-error-alternative)',
    muted: 'var(--mm-color-error-muted)',
    inverse: 'var(--mm-color-error-inverse)',
    'muted-hover': 'var(--mm-color-error-muted-hover)',
    'muted-pressed': 'var(--mm-color-error-muted-pressed)',
  },
  warning: {
    default: 'var(--mm-color-warning-default)',
    'default-hover': 'var(--mm-color-warning-default-hover)',
    'default-pressed': 'var(--mm-color-warning-default-pressed)',
    muted: 'var(--mm-color-warning-muted)',
    inverse: 'var(--mm-color-warning-inverse)',
    'muted-hover': 'var(--mm-color-warning-muted-hover)',
    'muted-pressed': 'var(--mm-color-warning-muted-pressed)',
  },
  success: {
    default: 'var(--mm-color-success-default)',
    'default-hover': 'var(--mm-color-success-default-hover)',
    'default-pressed': 'var(--mm-color-success-default-pressed)',
    muted: 'var(--mm-color-success-muted)',
    inverse: 'var(--mm-color-success-inverse)',
    'muted-hover': 'var(--mm-color-success-muted-hover)',
    'muted-pressed': 'var(--mm-color-success-muted-pressed)',
  },
  info: {
    default: 'var(--mm-color-info-default)',
    muted: 'var(--mm-color-info-muted)',
    inverse: 'var(--mm-color-info-inverse)',
  },
  accent01: {
    light: 'var(--mm-color-accent01-light)',
    normal: 'var(--mm-color-accent01-normal)',
    dark: 'var(--mm-color-accent01-dark)',
  },
  accent02: {
    light: 'var(--mm-color-accent02-light)',
    normal: 'var(--mm-color-accent02-normal)',
    dark: 'var(--mm-color-accent02-dark)',
  },
  accent03: {
    light: 'var(--mm-color-accent03-light)',
    normal: 'var(--mm-color-accent03-normal)',
    dark: 'var(--mm-color-accent03-dark)',
  },
  accent04: {
    light: 'var(--mm-color-accent04-light)',
    normal: 'var(--mm-color-accent04-normal)',
    dark: 'var(--mm-color-accent04-dark)',
  },
};
