export const typography = {
  fontSize: {
    // small screen typography
    's-display-md': 'var(--typography-s-display-md-font-size)',
    's-heading-lg': 'var(--typography-s-heading-lg-font-size)',
    's-heading-md': 'var(--typography-s-heading-md-font-size)',
    's-heading-sm': 'var(--typography-s-heading-sm-font-size)',
    's-body-lg': 'var(--typography-s-body-lg-regular-font-size)',
    's-body-md': 'var(--typography-s-body-md-font-size)',
    's-body-sm': 'var(--typography-s-body-sm-font-size)',
    's-body-xs': 'var(--typography-s-body-xs-font-size)',
    // large screen typography
    'l-display-md': 'var(--typography-l-display-md-font-size)',
    'l-heading-lg': 'var(--typography-l-heading-lg-font-size)',
    'l-heading-md': 'var(--typography-l-heading-md-font-size)',
    'l-heading-sm': 'var(--typography-l-heading-sm-font-size)',
    'l-body-lg': 'var(--typography-l-body-lg-medium-font-size)',
    'l-body-md': 'var(--typography-l-body-md-font-size)',
    'l-body-sm': 'var(--typography-l-body-sm-font-size)',
    'l-body-xs': 'var(--typography-l-body-xs-font-size)',
  },
  fontFamily: {
    centrano1: 'var(--font-family-centrano1)',
    'centrano1-regular': 'var(--font-family-centrano1)',
    'centrano1-regular-italic': 'var(--font-family-centrano1)',
    'centrano1-medium': 'var(--font-family-centrano1)',
    'centrano1-medium-italic': 'var(--font-family-centrano1)',
    'centrano1-bold': 'var(--font-family-centrano1)',
    'centrano1-bold-italic': 'var(--font-family-centrano1)',
    mmsans: 'var(--font-family-mmsans)',
    'mmsans-regular': 'var(--font-family-mmsans)',
    'mmsans-medium': 'var(--font-family-mmsans)',
    'mmsans-bold': 'var(--font-family-mmsans)',
    mmpoly: 'var(--font-family-mmpoly)',
    'mmpoly-regular': 'var(--font-family-mmpoly)',
  },
  letterSpacing: {
    // small screen typography
    's-display-md': 'var(--typography-s-display-md-letter-spacing)',
    's-heading-lg': 'var(--typography-s-heading-lg-letter-spacing)',
    's-heading-md': 'var(--typography-s-heading-md-letter-spacing)',
    's-heading-sm': 'var(--typography-s-heading-sm-letter-spacing)',
    's-body-lg': 'var(--typography-s-body-lg-regular-letter-spacing)',
    's-body-md': 'var(--typography-s-body-md-letter-spacing)',
    's-body-sm': 'var(--typography-s-body-sm-letter-spacing)',
    's-body-xs': 'var(--typography-s-body-xs-letter-spacing)',
    // large screen typography
    'l-display-md': 'var(--typography-l-display-md-letter-spacing)',
    'l-heading-lg': 'var(--typography-l-heading-lg-letter-spacing)',
    'l-heading-md': 'var(--typography-l-heading-md-letter-spacing)',
    'l-heading-sm': 'var(--typography-l-heading-sm-letter-spacing)',
    'l-body-lg': 'var(--typography-l-body-lg-medium-letter-spacing)',
    'l-body-md': 'var(--typography-l-body-md-letter-spacing)',
    'l-body-sm': 'var(--typography-l-body-sm-letter-spacing)',
    'l-body-xs': 'var(--typography-l-body-xs-letter-spacing)',
  },
  fontWeight: {
    // small screen typography
    's-display-md': 'var(--typography-s-display-md-font-weight)',
    's-heading-lg': 'var(--typography-s-heading-lg-font-weight)',
    's-heading-md': 'var(--typography-s-heading-md-font-weight)',
    's-heading-sm': 'var(--typography-s-heading-sm-font-weight)',
    's-body-lg': 'var(--font-weight-regular)',
    's-body-md': 'var(--typography-s-body-md-font-weight)',
    's-body-sm': 'var(--typography-s-body-sm-font-weight)',
    's-body-xs': 'var(--typography-s-body-xs-font-weight)',
    // large screen typography
    'l-display-md': 'var(--typography-l-display-md-font-weight)',
    'l-heading-lg': 'var(--typography-l-heading-lg-font-weight)',
    'l-heading-md': 'var(--typography-l-heading-md-font-weight)',
    'l-heading-sm': 'var(--typography-l-heading-sm-font-weight)',
    'l-body-lg': 'var(--font-weight-regular)',
    'l-body-md': 'var(--typography-l-body-md-font-weight)',
    'l-body-sm': 'var(--typography-l-body-sm-font-weight)',
    'l-body-xs': 'var(--typography-l-body-xs-font-weight)',
  },
  lineHeight: {
    // small screen typography
    's-display-md': 'var(--typography-s-display-md-line-height)',
    's-heading-lg': 'var(--typography-s-heading-lg-line-height)',
    's-heading-md': 'var(--typography-s-heading-md-line-height)',
    's-heading-sm': 'var(--typography-s-heading-sm-line-height)',
    's-body-lg': 'var(--typography-s-body-lg-regular-line-height)',
    's-body-md': 'var(--typography-s-body-md-line-height)',
    's-body-sm': 'var(--typography-s-body-sm-line-height)',
    's-body-xs': 'var(--typography-s-body-xs-line-height)',
    // large screen typography
    'l-display-md': 'var(--typography-l-display-md-line-height)',
    'l-heading-lg': 'var(--typography-l-heading-lg-line-height)',
    'l-heading-md': 'var(--typography-l-heading-md-line-height)',
    'l-heading-sm': 'var(--typography-l-heading-sm-line-height)',
    'l-body-lg': 'var(--typography-l-body-lg-medium-line-height)',
    'l-body-md': 'var(--typography-l-body-md-line-height)',
    'l-body-sm': 'var(--typography-l-body-sm-line-height)',
    'l-body-xs': 'var(--typography-l-body-xs-line-height)',
  },
};
