// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { AvatarToken } from './AvatarToken';

import { AvatarTokenSize } from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React web implementation of AvatarToken component
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  AvatarToken,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-WIP--MMDS-Components?node-id=128%3A2312',
  {
    props: {
      size: figma.enum('size', {
        Xs: AvatarTokenSize.Xs,
        Sm: AvatarTokenSize.Sm,
        Md: AvatarTokenSize.Md,
        Lg: AvatarTokenSize.Lg,
        Xl: AvatarTokenSize.Xl,
      }),
    },
    example: (props) => (
      <AvatarToken
        name="Ethereum"
        src="./assets/token-icons/eth.svg"
        {...props}
      />
    ),
  },
);
