// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { Toast } from './Toast';

import { ToastSeverity } from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of Toast component.
 *
 * - Figma `severity=Danger` maps to `ToastSeverity.Danger` in code.
 * - The branch Toast file exposes live `title` and `description` text
 *   properties. The action label now comes from the nested `Button` ->
 *   `ButtonBase` label so the design stays attached to the real Button
 *   component.
 * - `startAccessory (Figma only)` exists only for the `Default` severity
 *   variants to mirror the default-code-path accessory override story.
 * - The Figma component always shows a dismiss affordance, so the example
 *   always passes `onClose`.
 */

figma.connect(
  Toast,
  'https://www.figma.com/design/wM7fvpmK8hr8iA4TTkL8qV/%F0%9F%A6%8A-MMDS-Components?node-id=10690%3A2640',
  {
    props: {
      severity: figma.enum('severity', {
        Default: ToastSeverity.Default,
        Success: ToastSeverity.Success,
        Warning: ToastSeverity.Warning,
        Danger: ToastSeverity.Danger,
      }),
      title: figma.string('title'),
      description: figma.string('description'),
      actionButton: figma.nestedProps('ButtonBase', {
        label: figma.string('label'),
      }),
    },
    example: ({ severity, title, description, actionButton }) => {
      const resolvedActionButtonLabel = actionButton?.label || undefined;

      return (
        <Toast
          severity={severity}
          title={title}
          description={description}
          actionButtonLabel={resolvedActionButtonLabel}
          actionButtonOnPress={
            resolvedActionButtonLabel ? () => undefined : undefined
          }
          onClose={() => undefined}
        />
      );
    },
  },
);
