// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { AvatarFavicon } from './AvatarFavicon';

import { AvatarFaviconSize } from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of AvatarFavicon component
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  AvatarFavicon,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-WIP--MMDS-Components?node-id=225%3A5186',
  {
    props: {
      size: figma.enum('size', {
        Xs: AvatarFaviconSize.Xs,
        Sm: AvatarFaviconSize.Sm,
        Md: AvatarFaviconSize.Md,
        Lg: AvatarFaviconSize.Lg,
        Xl: AvatarFaviconSize.Xl,
      }),
    },
    example: (props) => (
      <AvatarFavicon
        name="Uniswap"
        src={{ uri: 'https://uniswap.org/favicon.ico' }}
        {...props}
      />
    ),
  },
);
