// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { HeaderRoot } from './HeaderRoot';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of HeaderRoot component.
 *
 * `title` is the only property that is not `(Figma Only)`, so the Figma-only
 * toggles drive the snippet rather than being mapped as props:
 * `leftSectionType` swaps the title for the nested `SelectButton`,
 * `showEndSection` gates `endAccessory`, and `endAccessoryNumber` decides how
 * many `endButton` instances resolve into it.
 */

figma.connect(
  HeaderRoot,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=15095-426',
  {
    props: {
      leftSection: figma.nestedProps('_LeftSection', {
        title: figma.enum('leftSectionType (Figma Only)', {
          title: figma.string('title'),
          button: undefined,
        }),
        selectButton: figma.children('SelectButton'),
      }),
      // figma.boolean + figma.nestedProps reflects live Figma values when shown;
      // the false fallback keeps property access safe without optional chaining
      // (Code Connect parser rejects ?.)
      endSection: figma.boolean('showEndSection (Figma Only)', {
        true: figma.nestedProps('_EndSection', {
          endButtons: figma.children('endButton*'),
        }),
        false: { endButtons: undefined },
      }),
    },
    example: ({ leftSection, endSection }) => (
      <HeaderRoot title={leftSection.title} endAccessory={endSection.endButtons}>
        {leftSection.selectButton}
      </HeaderRoot>
    ),
  },
);
