// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';

import { IconName } from '.';

// /////////////////////////////////////////////////////
// DO NOT EDIT - generated by generate-icon-figma-connect.ts
// Maps Figma icon glyph components to IconName for figma.instance() swaps.
// Regenerate: yarn generate:icon-figma-connect
// /////////////////////////////////////////////////////

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-307',
  {
    example: () => IconName.Accessibility,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11172',
  {
    example: () => IconName.Activity,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11065',
  {
    example: () => IconName.Add,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-188',
  {
    example: () => IconName.AddCard,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11069',
  {
    example: () => IconName.AddCircle,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11071',
  {
    example: () => IconName.AddSquare,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-326',
  {
    example: () => IconName.AfterHours,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11076',
  {
    example: () => IconName.Ai,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-311',
  {
    example: () => IconName.AlternateEmail,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-322',
  {
    example: () => IconName.AppleLogo,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11063',
  {
    example: () => IconName.Apps,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11087',
  {
    example: () => IconName.Arrow2Down,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11085',
  {
    example: () => IconName.Arrow2Left,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11084',
  {
    example: () => IconName.Arrow2Right,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11086',
  {
    example: () => IconName.Arrow2Up,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11081',
  {
    example: () => IconName.Arrow2UpRight,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11088',
  {
    example: () => IconName.ArrowCircleDown,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11089',
  {
    example: () => IconName.ArrowCircleUp,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11083',
  {
    example: () => IconName.ArrowDoubleLeft,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11082',
  {
    example: () => IconName.ArrowDoubleRight,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11078',
  {
    example: () => IconName.ArrowDown,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11098',
  {
    example: () => IconName.ArrowDropDownCircle,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11080',
  {
    example: () => IconName.ArrowLeft,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11079',
  {
    example: () => IconName.ArrowRight,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11077',
  {
    example: () => IconName.ArrowUp,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-267',
  {
    example: () => IconName.Attachment,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-318',
  {
    example: () => IconName.Backspace,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11115',
  {
    example: () => IconName.Ban,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-190',
  {
    example: () => IconName.Bank,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-191',
  {
    example: () => IconName.BankAssured,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11134',
  {
    example: () => IconName.Bold,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-235',
  {
    example: () => IconName.Book,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-240',
  {
    example: () => IconName.Bookmark,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-195',
  {
    example: () => IconName.Bridge,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-306',
  {
    example: () => IconName.Briefcase,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-298',
  {
    example: () => IconName.Bulb,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-330',
  {
    example: () => IconName.BuySell,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-275',
  {
    example: () => IconName.Cake,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-237',
  {
    example: () => IconName.Calculator,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-268',
  {
    example: () => IconName.Calendar,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-277',
  {
    example: () => IconName.Call,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-280',
  {
    example: () => IconName.Camera,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-308',
  {
    example: () => IconName.Campaign,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-320',
  {
    example: () => IconName.Candlestick,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-187',
  {
    example: () => IconName.Card,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11179',
  {
    example: () => IconName.Cash,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11117',
  {
    example: () => IconName.Category,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11127',
  {
    example: () => IconName.Chart,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11099',
  {
    example: () => IconName.Check,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11100',
  {
    example: () => IconName.CheckBold,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11105',
  {
    example: () => IconName.CircleX,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-321',
  {
    example: () => IconName.Clear,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11170',
  {
    example: () => IconName.Clock,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11171',
  {
    example: () => IconName.ClockFilled,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11104',
  {
    example: () => IconName.Close,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-211',
  {
    example: () => IconName.Cloud,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-210',
  {
    example: () => IconName.CloudDownload,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-209',
  {
    example: () => IconName.CloudUpload,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-228',
  {
    example: () => IconName.Code,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11178',
  {
    example: () => IconName.Coin,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-199',
  {
    example: () => IconName.Collapse,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11101',
  {
    example: () => IconName.Confirmation,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11166',
  {
    example: () => IconName.Connect,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-220',
  {
    example: () => IconName.Copy,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-221',
  {
    example: () => IconName.CopySuccess,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10503-4429',
  {
    example: () => IconName.CorporateFare,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-189',
  {
    example: () => IconName.CreditCheck,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-184',
  {
    example: () => IconName.CurrencyFranc,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11181',
  {
    example: () => IconName.CurrencyLira,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-185',
  {
    example: () => IconName.CurrencyPound,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11180',
  {
    example: () => IconName.CurrencyYuan,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11123',
  {
    example: () => IconName.Customize,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11108',
  {
    example: () => IconName.Danger,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-248',
  {
    example: () => IconName.Dark,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-249',
  {
    example: () => IconName.DarkFilled,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-243',
  {
    example: () => IconName.Data,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11138',
  {
    example: () => IconName.Description,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-258',
  {
    example: () => IconName.Details,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11126',
  {
    example: () => IconName.Diagram,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-229',
  {
    example: () => IconName.DocumentCode,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-206',
  {
    example: () => IconName.Download,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-303',
  {
    example: () => IconName.Draft,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-270',
  {
    example: () => IconName.EcoLeaf,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-222',
  {
    example: () => IconName.Edit,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11153',
  {
    example: () => IconName.EncryptedAdd,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-219',
  {
    example: () => IconName.Eraser,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11107',
  {
    example: () => IconName.Error,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11133',
  {
    example: () => IconName.Ethereum,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-186',
  {
    example: () => IconName.Exchange,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-197',
  {
    example: () => IconName.Expand,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-198',
  {
    example: () => IconName.ExpandVertical,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11056',
  {
    example: () => IconName.Explore,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11057',
  {
    example: () => IconName.ExploreFilled,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-203',
  {
    example: () => IconName.Export,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-305',
  {
    example: () => IconName.Extension,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11143',
  {
    example: () => IconName.Eye,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11144',
  {
    example: () => IconName.EyeSlash,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-310',
  {
    example: () => IconName.FaceId,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11114',
  {
    example: () => IconName.Feedback,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11136',
  {
    example: () => IconName.File,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11120',
  {
    example: () => IconName.Filter,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-312',
  {
    example: () => IconName.Fingerprint,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-273',
  {
    example: () => IconName.Fire,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11095',
  {
    example: () => IconName.FirstPage,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11167',
  {
    example: () => IconName.Flag,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11168',
  {
    example: () => IconName.Flash,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11169',
  {
    example: () => IconName.FlashSlash,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11128',
  {
    example: () => IconName.Flask,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-272',
  {
    example: () => IconName.Flower,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11137',
  {
    example: () => IconName.Folder,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-271',
  {
    example: () => IconName.Forest,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-241',
  {
    example: () => IconName.Gas,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-276',
  {
    example: () => IconName.Gift,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11059',
  {
    example: () => IconName.Global,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11058',
  {
    example: () => IconName.GlobalSearch,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11124',
  {
    example: () => IconName.Graph,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-253',
  {
    example: () => IconName.Hardware,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-317',
  {
    example: () => IconName.HashTag,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-231',
  {
    example: () => IconName.Heart,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-232',
  {
    example: () => IconName.HeartFilled,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-244',
  {
    example: () => IconName.Hierarchy,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11054',
  {
    example: () => IconName.Home,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11055',
  {
    example: () => IconName.HomeFilled,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11139',
  {
    example: () => IconName.Image,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11109',
  {
    example: () => IconName.Info,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-313',
  {
    example: () => IconName.Inventory,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-269',
  {
    example: () => IconName.Joystick,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-261',
  {
    example: () => IconName.Keep,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-262',
  {
    example: () => IconName.KeepFilled,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11160',
  {
    example: () => IconName.Key,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11096',
  {
    example: () => IconName.LastPage,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-251',
  {
    example: () => IconName.Light,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-250',
  {
    example: () => IconName.LightFilled,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-200',
  {
    example: () => IconName.Link,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-256',
  {
    example: () => IconName.Loading,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-295',
  {
    example: () => IconName.Location,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11161',
  {
    example: () => IconName.Lock,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11162',
  {
    example: () => IconName.LockSlash,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-201',
  {
    example: () => IconName.Login,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-202',
  {
    example: () => IconName.Logout,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-302',
  {
    example: () => IconName.Mail,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-297',
  {
    example: () => IconName.Map,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11062',
  {
    example: () => IconName.Menu,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11112',
  {
    example: () => IconName.MessageQuestion,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-234',
  {
    example: () => IconName.Messages,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-319',
  {
    example: () => IconName.MetamaskFoxOutline,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-278',
  {
    example: () => IconName.Mic,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11066',
  {
    example: () => IconName.Minus,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10260-420',
  {
    example: () => IconName.Minus,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11067',
  {
    example: () => IconName.MinusBold,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11072',
  {
    example: () => IconName.MinusSquare,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-225',
  {
    example: () => IconName.Mobile,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11173',
  {
    example: () => IconName.Money,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11176',
  {
    example: () => IconName.MoneyBag,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-224',
  {
    example: () => IconName.Monitor,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-296',
  {
    example: () => IconName.MountainFlag,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=13956-118',
  {
    example: () => IconName.Musd,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=13956-119',
  {
    example: () => IconName.MusdFilled,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-282',
  {
    example: () => IconName.MusicNote,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-245',
  {
    example: () => IconName.Notification,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11140',
  {
    example: () => IconName.PageInfo,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-301',
  {
    example: () => IconName.Palette,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11159',
  {
    example: () => IconName.PasswordCheck,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-255',
  {
    example: () => IconName.Pending,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-216',
  {
    example: () => IconName.People,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-218',
  {
    example: () => IconName.PersonCancel,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-260',
  {
    example: () => IconName.Pin,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11073',
  {
    example: () => IconName.Plant,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11129',
  {
    example: () => IconName.Plug,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11068',
  {
    example: () => IconName.PlusAndMinus,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11156',
  {
    example: () => IconName.PolicyAlert,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-325',
  {
    example: () => IconName.PopUp,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-300',
  {
    example: () => IconName.Print,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11111',
  {
    example: () => IconName.PriorityHigh,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11154',
  {
    example: () => IconName.PrivacyTip,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-194',
  {
    example: () => IconName.ProgrammingArrows,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-205',
  {
    example: () => IconName.Publish,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11164',
  {
    example: () => IconName.QrCode,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11113',
  {
    example: () => IconName.Question,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11165',
  {
    example: () => IconName.Receive,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-193',
  {
    example: () => IconName.Received,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11092',
  {
    example: () => IconName.Refresh,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11070',
  {
    example: () => IconName.RemoveMinus,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11110',
  {
    example: () => IconName.Report,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-274',
  {
    example: () => IconName.Rocket,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-238',
  {
    example: () => IconName.Save,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-239',
  {
    example: () => IconName.SaveFilled,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11177',
  {
    example: () => IconName.Saving,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11163',
  {
    example: () => IconName.Scan,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-196',
  {
    example: () => IconName.Search,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11145',
  {
    example: () => IconName.Security,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11148',
  {
    example: () => IconName.SecurityAlert,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11147',
  {
    example: () => IconName.SecurityCross,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11151',
  {
    example: () => IconName.SecurityKey,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11155',
  {
    example: () => IconName.SecuritySearch,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11150',
  {
    example: () => IconName.SecuritySlash,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11146',
  {
    example: () => IconName.SecurityTick,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11158',
  {
    example: () => IconName.SecurityTime,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11157',
  {
    example: () => IconName.SecurityUser,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-316',
  {
    example: () => IconName.Send,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-287',
  {
    example: () => IconName.SentimentDissatisfied,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-288',
  {
    example: () => IconName.SentimentNeutral,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-289',
  {
    example: () => IconName.SentimentSatisfied,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-290',
  {
    example: () => IconName.SentimentVerySatisfied,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11118',
  {
    example: () => IconName.Setting,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11119',
  {
    example: () => IconName.SettingFilled,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-204',
  {
    example: () => IconName.Share,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11152',
  {
    example: () => IconName.ShieldLock,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-294',
  {
    example: () => IconName.ShoppingBag,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-293',
  {
    example: () => IconName.ShoppingCart,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-324',
  {
    example: () => IconName.SidePanel,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-304',
  {
    example: () => IconName.SignalCellular,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11116',
  {
    example: () => IconName.Slash,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-233',
  {
    example: () => IconName.Sms,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-246',
  {
    example: () => IconName.Snaps,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-247',
  {
    example: () => IconName.SnapsPlus,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11121',
  {
    example: () => IconName.Sort,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11122',
  {
    example: () => IconName.SortByAlpha,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11075',
  {
    example: () => IconName.Sparkle,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-291',
  {
    example: () => IconName.Speed,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-242',
  {
    example: () => IconName.Speedometer,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11135',
  {
    example: () => IconName.Square,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11074',
  {
    example: () => IconName.Stake,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-230',
  {
    example: () => IconName.Star,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-227',
  {
    example: () => IconName.StarFilled,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11094',
  {
    example: () => IconName.Start,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-292',
  {
    example: () => IconName.Storefront,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-236',
  {
    example: () => IconName.Student,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11090',
  {
    example: () => IconName.SwapHorizontal,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11091',
  {
    example: () => IconName.SwapVertical,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-314',
  {
    example: () => IconName.TabClose,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-285',
  {
    example: () => IconName.TableRow,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-226',
  {
    example: () => IconName.Tablet,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-192',
  {
    example: () => IconName.Tag,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=14337-350',
  {
    example: () => IconName.Telegram,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=13518-1017',
  {
    example: () => IconName.Telegram,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-263',
  {
    example: () => IconName.ThumbDown,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-264',
  {
    example: () => IconName.ThumbDownFilled,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-265',
  {
    example: () => IconName.ThumbUp,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-266',
  {
    example: () => IconName.ThumbUpFilled,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-252',
  {
    example: () => IconName.Tint,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-299',
  {
    example: () => IconName.Translate,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-223',
  {
    example: () => IconName.Trash,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11149',
  {
    example: () => IconName.TrendDown,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11125',
  {
    example: () => IconName.TrendUp,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-328',
  {
    example: () => IconName.Trophy,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11093',
  {
    example: () => IconName.Undo,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11097',
  {
    example: () => IconName.Unfold,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-259',
  {
    example: () => IconName.Unpin,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-207',
  {
    example: () => IconName.Upload,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-208',
  {
    example: () => IconName.UploadFile,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-254',
  {
    example: () => IconName.Usb,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-212',
  {
    example: () => IconName.User,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-217',
  {
    example: () => IconName.UserCheck,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-215',
  {
    example: () => IconName.UserCircle,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-213',
  {
    example: () => IconName.UserCircleAdd,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-214',
  {
    example: () => IconName.UserCircleRemove,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11102',
  {
    example: () => IconName.Verified,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11103',
  {
    example: () => IconName.VerifiedFilled,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-281',
  {
    example: () => IconName.Videocam,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-286',
  {
    example: () => IconName.ViewColumn,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-279',
  {
    example: () => IconName.ViewInAr,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-283',
  {
    example: () => IconName.VolumeOff,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-284',
  {
    example: () => IconName.VolumeUp,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11174',
  {
    example: () => IconName.Wallet,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11175',
  {
    example: () => IconName.WalletFilled,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11106',
  {
    example: () => IconName.Warning,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-309',
  {
    example: () => IconName.WebTraffic,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11064',
  {
    example: () => IconName.Widgets,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11141',
  {
    example: () => IconName.Wifi,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10261-11142',
  {
    example: () => IconName.WifiOff,
  },
);

figma.connect(
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=10271-315',
  {
    example: () => IconName.X,
  },
);
