// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React, { useState } from 'react';

import { Checkbox } from './Checkbox';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of Checkbox component
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-WIP--MMDS-Components?node-id=385%3A18907',
  {
    props: {
      isDisabled: figma.boolean('isDisabled'),
      isInvalid: figma.boolean('isInvalid'),
      label: figma.nestedProps('Label', {
        text: figma.string('Label text'),
      }),
    },
    example: ({ isDisabled, isInvalid, label, ...props }) => {
      const [isSelected, setIsSelected] = useState(false);
      return (
        <Checkbox
          id="checkbox-example"
          isSelected={isSelected}
          isDisabled={isDisabled}
          isInvalid={isInvalid}
          label={label.text}
          onChange={(prevState) => {
            setIsSelected(!prevState);
          }}
          {...props}
        />
      );
    },
  },
);
