// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { TitleHub } from './TitleHub';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of TitleHub component.
 *
 * Slot architecture (Figma node 15293:24032):
 * - `titleEndAccessory`, `amountEndAccessory`, and `bottomLabelEndAccessory` resolve
 *   nested connected instances via `figma.children()` when their visibility toggles are on.
 * - `BottomLabelRow` is a Figma slot for custom bottom row content (`bottomAccessory`).
 * - `bottomLabel` is read from the `bottomLabel` text layer via `figma.textContent()`.
 */

figma.connect(
  TitleHub,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=15293-24032',
  {
    props: {
      title: figma.string('title'),
      amount: figma.string('amount'),
      titleEndAccessory: figma.boolean('titleEndAccessory', {
        true: figma.children('titleEndAccessory'),
        false: undefined,
      }),
      amountEndAccessory: figma.boolean('amountEndAccessory', {
        true: figma.children('amountEndAccessory'),
        false: undefined,
      }),
      bottomLabel: figma.textContent('bottomLabel'),
      bottomLabelEndAccessory: figma.boolean('bottomLabelEndAccessory', {
        true: figma.children('bottomLabelEndAccessory'),
        false: undefined,
      }),
      bottomAccessory: figma.slot('BottomLabelRow'),
    },
    example: ({
      title,
      amount,
      titleEndAccessory,
      amountEndAccessory,
      bottomLabel,
      bottomLabelEndAccessory,
      bottomAccessory,
    }) => (
      <TitleHub
        title={title}
        amount={amount}
        titleEndAccessory={titleEndAccessory}
        amountEndAccessory={amountEndAccessory}
        bottomLabel={bottomLabel}
        bottomLabelEndAccessory={bottomLabelEndAccessory}
        bottomAccessory={bottomAccessory}
      />
    ),
  },
);
