// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import { IconName, TagSeverity } from '@metamask/design-system-shared';
import React from 'react';

import { Icon, IconColor, IconSize } from '../Icon';
import { Tag } from '../Tag';

import { TitleHub } from './TitleHub';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of TitleHub component.
 *
 * - `titleEndAccessory` and `amountEndAccessory` are visibility toggles in Figma;
 *   the example uses placeholder `Tag` and `Icon` children when enabled.
 * - `bottomRow` toggles the nested `_BottomRow` instance (`bottomLabel` /
 *   `bottomLabelEndAccessory`). Tag-only props on `titleEndAccessory` are omitted.
 */

figma.connect(
  TitleHub,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=15293-24032',
  {
    props: {
      title: figma.string('title'),
      amount: figma.string('amount'),
      titleEndAccessory: figma.boolean('titleEndAccessory'),
      amountEndAccessory: figma.boolean('amountEndAccessory'),
      bottomRowVisible: figma.boolean('bottomRow'),
      bottomRow: figma.nestedProps('_BottomRow', {
        bottomLabel: figma.string('bottomLabel'),
        bottomLabelEndAccessory: figma.boolean('bottomLabelEndAccessory'),
      }),
    },
    example: ({
      title,
      amount,
      titleEndAccessory,
      amountEndAccessory,
      bottomRowVisible,
      bottomRow,
    }) => {
      const resolvedAmount = amount || undefined;

      const resolvedTitleEndAccessory = titleEndAccessory ? (
        <Tag severity={TagSeverity.Warning}>Testnet</Tag>
      ) : undefined;

      const resolvedAmountEndAccessory = amountEndAccessory ? (
        <Icon
          name={IconName.Info}
          size={IconSize.Sm}
          color={IconColor.IconAlternative}
        />
      ) : undefined;

      const resolvedBottomLabel = bottomRowVisible
        ? bottomRow.bottomLabel
        : undefined;

      const resolvedBottomLabelEndAccessory =
        bottomRowVisible && bottomRow.bottomLabelEndAccessory ? (
          <Icon name={IconName.Info} size={IconSize.Xs} />
        ) : undefined;

      return (
        <TitleHub
          title={title}
          amount={resolvedAmount}
          titleEndAccessory={resolvedTitleEndAccessory}
          amountEndAccessory={resolvedAmountEndAccessory}
          bottomLabel={resolvedBottomLabel}
          bottomLabelEndAccessory={resolvedBottomLabelEndAccessory}
        />
      );
    },
  },
);
