// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { BottomSheetOverlay } from './BottomSheetOverlay';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of BottomSheetOverlay component.
 */

figma.connect(
  BottomSheetOverlay,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=16576-21410',
  {
    example: () => <BottomSheetOverlay onPress={() => undefined} />,
  },
);
