// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { BadgeStatus } from './BadgeStatus';

import { BadgeStatusSize, BadgeStatusStatus } from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React web implementation of BadgeStatus component
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  BadgeStatus,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-WIP--MMDS-Components?node-id=623%3A3377',
  {
    props: {
      size: figma.enum('size', {
        Md: BadgeStatusSize.Md,
        Lg: BadgeStatusSize.Lg,
      }),
      status: figma.enum('status', {
        'Active (green)': BadgeStatusStatus.Active,
        'Inactive (green border)': BadgeStatusStatus.Inactive,
        'Disconnected (grey)': BadgeStatusStatus.Disconnected,
        'New (blue)': BadgeStatusStatus.New,
        'Attention (red)': BadgeStatusStatus.Attention,
      }),
      hasBorder: figma.boolean('hasBorder'),
    },
    example: ({ status, hasBorder, ...props }) => (
      <BadgeStatus status={status} hasBorder={hasBorder} {...props} />
    ),
  },
);
