// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { ButtonSize } from '../Button';
import { IconName } from '../Icon';

import { BottomSheetFooter } from './BottomSheetFooter';

import { ButtonsAlignment } from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of BottomSheetFooter component.
 */

figma.connect(
  BottomSheetFooter,
  'https://www.figma.com/design/FhTeTCS0k1PHBab25vXl79/refactor--BottomSheet?node-id=16452-20245',
  {
    props: {
      buttonsAlignment: figma.enum('variant', {
        horizontal: ButtonsAlignment.Horizontal,
        vertical: ButtonsAlignment.Vertical,
      }),
      primaryButtonBase: figma.boolean('hasPrimary', {
        true: figma.nestedProps('primaryButton/_ButtonBase', {
          label: figma.string('label'),
          size: figma.enum('size', {
            Lg: ButtonSize.Lg,
          }),
          startIconName: figma.boolean('startIcon (Figma Only)', {
            true: IconName.Add,
            false: undefined,
          }),
          endIconName: figma.boolean('endIcon (Figma Only)', {
            true: IconName.Add,
            false: undefined,
          }),
        }),
        false: undefined,
      }),
      primaryButtonState: figma.boolean('hasPrimary', {
        true: figma.nestedProps('primaryButton', {
          isDisabled: figma.boolean('isDisabled', {
            false: false,
            true: true,
          }),
          isDanger: figma.boolean('isDanger', {
            false: false,
            true: true,
          }),
          isInverse: figma.boolean('isInverse', {
            false: false,
            true: true,
          }),
          isLoading: figma.boolean('isLoading', {
            false: false,
            true: true,
          }),
        }),
        false: undefined,
      }),
      secondaryButtonBase: figma.boolean('hasSecondary', {
        true: figma.nestedProps('secondaryButton/_ButtonBase', {
          label: figma.string('label'),
          size: figma.enum('size', {
            Lg: ButtonSize.Lg,
          }),
          startIconName: figma.boolean('startIcon (Figma Only)', {
            true: IconName.Add,
            false: undefined,
          }),
          endIconName: figma.boolean('endIcon (Figma Only)', {
            true: IconName.Add,
            false: undefined,
          }),
        }),
        false: undefined,
      }),
      secondaryButtonState: figma.boolean('hasSecondary', {
        true: figma.nestedProps('secondaryButton', {
          isDisabled: figma.boolean('isDisabled', {
            false: false,
            true: true,
          }),
          isDanger: figma.boolean('isDanger', {
            false: false,
            true: true,
          }),
          isInverse: figma.boolean('isInverse', {
            false: false,
            true: true,
          }),
          isLoading: figma.boolean('isLoading', {
            false: false,
            true: true,
          }),
        }),
        false: undefined,
      }),
    },
    example: ({
      buttonsAlignment,
      primaryButtonBase,
      primaryButtonState,
      secondaryButtonBase,
      secondaryButtonState,
    }) => {
      const resolvedPrimaryButtonProps =
        primaryButtonBase && primaryButtonState
          ? {
              children: primaryButtonBase.label,
              size: primaryButtonBase.size,
              startIconName: primaryButtonBase.startIconName,
              endIconName: primaryButtonBase.endIconName,
              isDisabled: primaryButtonState.isDisabled,
              isDanger: primaryButtonState.isDanger,
              isInverse: primaryButtonState.isInverse,
              isLoading: primaryButtonState.isLoading,
              onPress: () => undefined,
            }
          : undefined;

      const resolvedSecondaryButtonProps =
        secondaryButtonBase && secondaryButtonState
          ? {
              children: secondaryButtonBase.label,
              size: secondaryButtonBase.size,
              startIconName: secondaryButtonBase.startIconName,
              endIconName: secondaryButtonBase.endIconName,
              isDisabled: secondaryButtonState.isDisabled,
              isDanger: secondaryButtonState.isDanger,
              isInverse: secondaryButtonState.isInverse,
              isLoading: secondaryButtonState.isLoading,
              onPress: () => undefined,
            }
          : undefined;

      return (
        <BottomSheetFooter
          buttonsAlignment={buttonsAlignment}
          primaryButtonProps={resolvedPrimaryButtonProps}
          secondaryButtonProps={resolvedSecondaryButtonProps}
        />
      );
    },
  },
);
