// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { BottomSheetDialog } from './BottomSheetDialog';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of BottomSheetDialog component.
 */

figma.connect(
  BottomSheetDialog,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=16571-1745',
  {
    props: {
      isInteractable: figma.boolean('isInteractable'),
      bottomSheetContent: figma.slot('BottomSheetContent'),
    },
    example: ({ isInteractable, bottomSheetContent }) => (
      <BottomSheetDialog isInteractable={isInteractable}>
        {bottomSheetContent}
      </BottomSheetDialog>
    ),
  },
);
