// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { BottomSheetFooter } from '../BottomSheetFooter';
import { BottomSheetHeader } from '../BottomSheetHeader';
import { Box } from '../Box';
import { Text } from '../Text';

import { BottomSheetDialog } from './BottomSheetDialog';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of BottomSheetDialog component.
 *
 * - Do not use `figma.slot('BottomSheetContent')` — that emits a nested
 *   placeholder function in Dev Mode. Children match Storybook / BottomSheet
 *   composition instead (Header + content + Footer).
 * - Figma `BottomSheetHeader` is a show/hide boolean; the example always
 *   includes the header (same pattern as BottomSheet Code Connect) and maps
 *   nested title / back / close from BottomSheetHeader.
 */

figma.connect(
  BottomSheetDialog,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=16571-1745',
  {
    props: {
      isInteractable: figma.boolean('isInteractable'),
      header: figma.nestedProps('BottomSheetHeader', {
        title: figma.string('title'),
        onBack: figma.boolean('startAccessory', {
          true: () => undefined,
          false: undefined,
        }),
        onClose: figma.boolean('endAccessory', {
          true: () => undefined,
          false: undefined,
        }),
      }),
    },
    example: ({ isInteractable, header }) => (
      <BottomSheetDialog isInteractable={isInteractable}>
        <BottomSheetHeader onBack={header.onBack} onClose={header.onClose}>
          {header.title}
        </BottomSheetHeader>
        <Box twClassName="p-4">
          <Text>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </Text>
        </Box>
        <BottomSheetFooter
          secondaryButtonProps={{
            children: 'Cancel',
            onPress: () => undefined,
          }}
          primaryButtonProps={{
            children: 'Confirm',
            onPress: () => undefined,
          }}
        />
      </BottomSheetDialog>
    ),
  },
);
