// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { BottomSheetFooter } from '../BottomSheetFooter';
import { BottomSheetHeader } from '../BottomSheetHeader';
import { Box } from '../Box';
import { Text } from '../Text';

import { BottomSheet } from './BottomSheet';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of BottomSheet component.
 *
 * - Figma `hasKeyboard` is a visual preview variant only and is not mapped to code.
 * - Footer button labels use realistic defaults; `variant (Figma only)` on
 *   BottomSheetFooter is omitted.
 */

figma.connect(
  BottomSheet,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=16571-1026',
  {
    props: {
      isFullscreen: figma.boolean('isFullscreen', {
        false: false,
        true: true,
      }),
      header: figma.nestedProps('BottomSheetHeader', {
        title: figma.string('title'),
      }),
    },
    example: ({ isFullscreen, header }) => (
      <BottomSheet isFullscreen={isFullscreen} onClose={() => undefined}>
        <BottomSheetHeader onClose={() => undefined}>
          {header.title}
        </BottomSheetHeader>
        <Box twClassName="p-4">
          <Text>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </Text>
        </Box>
        <BottomSheetFooter
          secondaryButtonProps={{
            children: 'Cancel',
            onPress: () => undefined,
          }}
          primaryButtonProps={{
            children: 'Confirm',
            onPress: () => undefined,
          }}
        />
      </BottomSheet>
    ),
  },
);
