// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import { IconName } from '@metamask/design-system-shared';
import React from 'react';

import { BadgeIcon } from './BadgeIcon';

/**
 * -- This file was auto-generated by Code Connect --
 * React web implementation of BadgeIcon component
 */

figma.connect(
  BadgeIcon,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=1973-2439',
  {
    example: () => (
      <BadgeIcon
        iconName={IconName.Close} // Check the icon name in figma
      />
    ),
  },
);
