// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { SectionHeader } from './SectionHeader';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of SectionHeader component
 */
figma.connect(
  SectionHeader,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=9624-8420',
  {
    props: {
      title: figma.string('title'),
      startAccessory: figma.boolean('startAccessory', {
        true: figma.children('startAccessory'),
        false: undefined,
      }),
      titleAccessory: figma.boolean('titleAccessory', {
        true: figma.children('titleAccessory'),
        false: undefined,
      }),
      endAccessory: figma.boolean('endAccessory', {
        true: figma.children('endAccessory'),
        false: undefined,
      }),
      children: figma.boolean('subtitle', {
        true: figma.children('children'),
        false: undefined,
      }),
    },
    example: ({
      title,
      startAccessory,
      titleAccessory,
      endAccessory,
      children,
    }) => (
      <SectionHeader
        title={title}
        startAccessory={startAccessory}
        titleAccessory={titleAccessory}
        endAccessory={endAccessory}
      >
        {children}
      </SectionHeader>
    ),
  },
);
