name: Test Storybook

on:
  workflow_call:

jobs:
  test-storybook:
    name: Test Storybook (accessibility & stories) (${{ matrix.label }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - label: React
            command: yarn test:storybook:react
          - label: React Native 1/3
            command: yarn workspace @metamask/storybook-react-native test-storybook --shard=1/3
          - label: React Native 2/3
            command: yarn workspace @metamask/storybook-react-native test-storybook --shard=2/3
          - label: React Native 3/3
            command: yarn workspace @metamask/storybook-react-native test-storybook --shard=3/3
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Build packages
        run: yarn build
      - name: Run Storybook tests
        run: ${{ matrix.command }}
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi
