name: Test Storybook

on:
  workflow_call:

jobs:
  test-storybook:
    name: Test Storybook (accessibility & stories) (${{ matrix.label }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - label: React
            command: yarn test:storybook:react
            retry: 'false'
          - label: React Native
            command: yarn test:storybook:react-native
            retry: 'true'
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Build packages
        run: yarn build
      - name: Run Storybook tests
        if: matrix.retry != 'true'
        run: ${{ matrix.command }}
      - name: Run Storybook tests
        if: matrix.retry == 'true'
        uses: MetaMask/action-retry-command@v1
        with:
          command: ${{ matrix.command }}
          max-retries: 3
        env:
          NODE_OPTIONS: --max-old-space-size=4096
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi
